import { useState } from 'react';
import type { Topic, Mode, Problem, Detective, Card } from './types';
import { parseNumber } from './learning';
import Diagram from './Diagram';
export default function Activity({ topic, mode, onAward, onMode }: { topic: Topic; mode: Mode; onAward: (key: string) => void; onMode: (mode: Mode) => void }) {
  const items = mode === 'solve' ? topic.problems : mode === 'detect' ? topic.detectives : topic.cards;
  const [queue, setQueue] = useState(() => items.map((_, i) => i));
  const [index, setIndex] = useState(0);
  const [hints, setHints] = useState(0);
  const [solved, setSolved] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [answer, setAnswer] = useState('');
  const [feedback, setFeedback] = useState('');
  const [good, setGood] = useState(false);
  const p = items[queue[index]];
  const award = () => onAward([topic.id, mode, queue[index], JSON.stringify(p)].join('|'));
  function reset() { setHints(0); setSolved(false); setRevealed(false); setAnswer(''); setFeedback(''); setGood(false); }
  function next(revisit = false) { if (revisit) setQueue(q => [...q, q[index]]); reset(); setIndex(i => i + 1); }
  if (!p) return <article className="panel"><div className="cardbody"><span className="badge">EXPLORATION COMPLETE</span><h2 style={{ marginTop: 30 }}>Look at what you worked through.</h2><p className="formulanote">You practiced {items.length} {mode === 'recall' ? 'ideas' : 'challenges'}. Explain one to someone, take a break, or explore another way.</p><div className="actions"><button onClick={() => { reset(); setQueue(items.map((_, i) => i)); setIndex(0); }}>Try this set again</button><button className="secondary" onClick={() => onMode(mode === 'solve' ? 'detect' : mode === 'detect' ? 'recall' : 'solve')}>{mode === 'solve' ? 'Try word detective' : mode === 'detect' ? 'Try formula flip' : 'Back to solving'} →</button></div></div></article>;
  return <article className="panel"><div className="paneltop"><span className="badge">{mode === 'solve' ? 'LET’S WORK IT OUT' : mode === 'detect' ? 'FIND THE MISSION' : 'RETRIEVE, THEN REVEAL'}</span><span className="muted">{index >= items.length ? 'Revisit · ' : ''}{index + 1} of {queue.length}</span></div>
    {mode === 'solve' && (() => { const problem = p as Problem; return <div className="problemgrid"><div className="problem"><h2>{problem.title}</h2><p>{problem.text}</p><form onSubmit={e => { e.preventDefault(); if (solved) return; const value = parseNumber(answer); if (value === null) { setFeedback('Try a number such as 12, 2.5, or 3/4.'); setGood(false); } else if (Math.abs(value - problem.answer) < 1e-8) { setSolved(true); setGood(true); award(); setFeedback('You found it! ' + problem.steps.at(-1)); } else { setGood(false); setFeedback('Not quite yet. Check what you’re finding, then try a hint. You’ve got room to rethink.'); } }}><label className="label" htmlFor="answer">Your answer <span className="muted">(number or fraction)</span></label><div className="answerline"><input id="answer" type="text" autoComplete="off" value={answer} onChange={e => setAnswer(e.target.value)} placeholder="?" disabled={solved} aria-describedby="result" /><span>{problem.unit}</span><button disabled={solved}>Check</button></div></form><div id="result" role="status">{feedback && <div className={`feedback ${good ? 'success' : ''}`}>{feedback}</div>}</div>{hints > 0 && <div className="steps">{problem.steps.slice(0, hints).map((s, i) => <p key={i}><strong>{i + 1}.</strong> {s}</p>)}</div>}<div className="actions">{hints < problem.steps.length && <button className="hint" onClick={() => setHints(h => h + 1)}>✧ {hints ? 'Show the next step' : 'A little hint, please'}</button>}{solved && <button onClick={() => next()}>Next adventure →</button>}</div></div><div className="visual"><Diagram problem={problem} /></div></div>; })()}
    {mode === 'detect' && (() => { const d = p as Detective; return <div className="cardbody"><h2>{d.text}</h2><p className="formulanote">First ask: what quantity is missing? Choose the plan before doing the arithmetic.</p><div className="options">{d.options.map((o, i) => <button key={i} disabled={solved} onClick={() => { if (solved) return; const correct = i === d.correct; setGood(correct); if (correct) { setSolved(true); award(); setFeedback('Exactly. ' + d.why); } else setFeedback('Look again at what needs to be measured or found. Is it a total, a missing part, a surface, or a number of groups?'); }}>{String.fromCharCode(65 + i)}. &nbsp;{o}</button>)}</div><div role="status">{feedback && <div className={`feedback ${good ? 'success' : ''}`}>{feedback}</div>}</div>{solved && <button onClick={() => next()}>Next mystery →</button>}</div>; })()}
    {mode === 'recall' && (() => { const c = p as Card; return <div className="cardbody"><h2>{c.prompt}</h2><p className="formulanote">Say it, sketch it, or write it on paper before you flip.</p><div className="formula">{revealed ? c.formula : 'Think it. Then flip it.'}</div>{revealed ? <><p className="formulanote">{c.why}</p><div className="steps">{c.example}</div><p className="muted">How did that feel? Both choices earn a spark.</p><div className="actions"><button onClick={() => { award(); next(); }}>I remembered it ✦</button><button className="secondary" onClick={() => { award(); next(true); }}>Let’s revisit this one</button></div></> : <button onClick={() => setRevealed(true)}>Reveal the idea ↻</button>}</div>; })()}
  </article>;
}
