import type { Topic } from './types';
export const CURRICULUM: Topic[] = [
{id:'area',name:'Area',subtitle:'Explore area. See the space. Solve the mystery.',problems:[
// --- Warm-up: the four basic shapes ---
{title:'A space for your ideas',text:'Your rectangular art board is 8 cm long and 5 cm wide. How much space is there for your artwork?',answer:40,unit:'cm²',shape:'rectangle',a:8,b:5,steps:['Find the space inside the board. That means area, measured in square units.','A rectangle has rows of equal squares. Use area = length × width.','Substitute: 8 × 5 = 40. The area is 40 cm².']},
{title:'Build a reading nook',text:'A square rug has sides of 6 feet. What area of the floor will it cover?',answer:36,unit:'ft²',shape:'square',a:6,b:6,steps:['We want the floor covered, so find area.','A square is a rectangle with equal sides: area = side × side.','6 × 6 = 36 square feet.']},
{title:'Design a pennant',text:'A triangular pennant has a base of 10 cm and a perpendicular height of 6 cm. What is its area?',answer:30,unit:'cm²',shape:'triangle',a:10,b:6,steps:['Find the space inside the triangle. The height is perpendicular to the base.','A triangle takes up half of a matching parallelogram: area = base × height ÷ 2.','10 × 6 ÷ 2 = 30 cm².']},
{title:'A slanted splash of color',text:'A parallelogram sticker has a base of 9 cm and a perpendicular height of 4 cm. Find its area.',answer:36,unit:'cm²',shape:'parallelogram',a:9,b:4,steps:['Use the perpendicular height, not the slanted side.','Sliding a triangular piece from one side to the other makes a rectangle. Area = base × height.','9 × 4 = 36 cm².']},
// --- Missing measurements ---
{title:'The garden mystery',text:'A rectangular garden has an area of 48 m² and a length of 8 m. How wide is it?',answer:6,unit:'m',shape:'rectangle',a:8,b:'?',steps:['We already know the area. The missing measurement is width, in meters.','Area = length × width, so 48 = 8 × width. Undo multiplication with division.','48 ÷ 8 = 6. The width is 6 m.']},
{title:'The missing height',text:'A triangular flag has an area of 36 in² and a base of 9 in. What is its perpendicular height?',answer:8,unit:'in',shape:'triangle',a:9,b:'?',steps:['We know the area and base. We need the height.','Area = base × height ÷ 2, so 36 = 9 × height ÷ 2. Double both sides first: 72 = 9 × height.','72 ÷ 9 = 8. The height is 8 inches.']},
{title:'A parallelogram puzzle',text:'A parallelogram has an area of 52.5 cm² and a perpendicular height of 7 cm. How long is its base?',answer:7.5,unit:'cm',shape:'parallelogram',a:'?',b:7,steps:['Area = base × height. We know area and height.','52.5 = base × 7. Divide to find the missing factor.','52.5 ÷ 7 = 7.5 cm.']},
// --- Decimals and fractions as side lengths ---
{title:'A tiny studio',text:'A rectangular tabletop is 2.5 m long and 1.2 m wide. How much surface area does it have?',answer:3,unit:'m²',shape:'rectangle',a:2.5,b:1.2,steps:['Surface area here means the flat top, a rectangle.','Use length × width: 2.5 × 1.2.','25 × 12 = 300. Put back two decimal places: 3.00 m².']},
{title:'Fractional floor plan',text:'A closet floor is 4½ ft long and 2⅔ ft wide. What is its area?',answer:12,unit:'ft²',shape:'rectangle',a:4.5,b:'2⅔',steps:['Area = length × width, even when the sides are mixed numbers.','Rewrite as improper fractions: 4½ = 9/2 and 2⅔ = 8/3.','9/2 × 8/3 = 72/6 = 12 ft².']},
{title:'One last triangle',text:'A triangular sail has a base of 7 m and a perpendicular height of 5 m. Find its area.',answer:17.5,unit:'m²',shape:'triangle',a:7,b:5,steps:['Find area using the base and perpendicular height.','Area = base × height ÷ 2.','7 × 5 = 35. Half of 35 is 17.5 m².']},
{title:'Half-inch squares',text:'A sticky note is 3½ in by 3½ in. What is its area?',answer:12.25,unit:'in²',shape:'square',a:3.5,b:3.5,steps:['A square: area = side × side.','3½ = 7/2. So 7/2 × 7/2 = 49/4.','49/4 = 12¼ = 12.25 in².']},
// --- Right triangles and rectangles ---
{title:'Cut on the diagonal',text:'A rectangular sandwich is 10 cm by 6 cm. You cut it corner to corner. What is the area of one triangular half?',answer:30,unit:'cm²',shape:'triangle',a:10,b:6,steps:['The diagonal splits the rectangle into two equal right triangles.','Rectangle area: 10 × 6 = 60 cm². Each triangle is half of that.','60 ÷ 2 = 30 cm². Same as base × height ÷ 2 with the two legs.']},
// --- Trapezoids, rhombuses, kites ---
{title:'The trapezoid table',text:'A trapezoid tabletop has parallel sides of 8 ft and 12 ft, and the distance between them is 5 ft. Find its area.',answer:50,unit:'ft²',shape:'text',visual:'(8 + 12) ÷ 2 × 5',steps:['A trapezoid has two parallel bases. Average them to make an equal-area rectangle.','(8 + 12) ÷ 2 = 10. That is the average base.','10 × 5 = 50 ft².']},
{title:'Splitting the trapezoid',text:'A right trapezoid has bases 6.5 m and 9.5 m and height 4 m. Find its area by splitting it into a rectangle and a triangle.',answer:32,unit:'m²',shape:'text',visual:'26 + 6',steps:['Decompose: a 6.5 × 4 rectangle plus a triangle with base 9.5 − 6.5 = 3 and height 4.','Rectangle: 6.5 × 4 = 26. Triangle: 3 × 4 ÷ 2 = 6.','26 + 6 = 32 m². Check: (6.5 + 9.5) ÷ 2 × 4 = 32. Both ways agree.']},
{title:'A diamond in the rough',text:'A rhombus-shaped tile has diagonals of 10 cm and 6 cm. What is its area?',answer:30,unit:'cm²',shape:'text',visual:'10 × 6 ÷ 2',steps:['The diagonals cross at right angles and cut the rhombus into four right triangles.','Those four triangles fill exactly half of a 10 × 6 rectangle.','10 × 6 ÷ 2 = 30 cm².']},
{title:'Fly the kite',text:'A kite has diagonals of 14 in and 9 in. Find its area.',answer:63,unit:'in²',shape:'text',visual:'14 × 9 ÷ 2',steps:['A kite works like a rhombus: its diagonals are perpendicular.','Area = diagonal × diagonal ÷ 2.','14 × 9 = 126. Half is 63 in².']},
// --- Composite figures ---
{title:'Room for two',text:'A craft mat is made from two non-overlapping rectangles. One is 6 cm by 4 cm; the other is 3 cm by 2 cm. What is their total area?',answer:30,unit:'cm²',shape:'text',visual:'24 + 6',steps:['The two pieces do not overlap, so we can add their areas.','First rectangle: 6 × 4 = 24 cm². Second rectangle: 3 × 2 = 6 cm².','24 + 6 = 30 cm² in all.']},
{title:'The L-shaped room',text:'An L-shaped room fits inside a 10 m by 8 m rectangle, but a 4 m by 3 m corner is missing. What is the floor area?',answer:68,unit:'m²',shape:'text',visual:'80 − 12',steps:['Start with the big rectangle, then subtract the missing corner.','Big rectangle: 10 × 8 = 80 m². Missing corner: 4 × 3 = 12 m².','80 − 12 = 68 m².']},
{title:'House shape',text:'A house-shaped sign is a 12 cm by 5 cm rectangle with a triangle roof on top. The roof has base 12 cm and height 4 cm. Find the total area.',answer:84,unit:'cm²',shape:'text',visual:'60 + 24',steps:['Decompose into a rectangle and a triangle that share the 12 cm edge.','Rectangle: 12 × 5 = 60. Triangle: 12 × 4 ÷ 2 = 24.','60 + 24 = 84 cm².']},
{title:'Paint the wall',text:'A wall is 12 ft wide and 8 ft tall. It has one window that is 3 ft by 4 ft. How much wall needs paint?',answer:84,unit:'ft²',shape:'text',visual:'96 − 12',steps:['Paint covers the wall but not the window. Subtract the window area.','Wall: 12 × 8 = 96 ft². Window: 3 × 4 = 12 ft².','96 − 12 = 84 ft².']},
{title:'The hexagon patio',text:'A regular hexagon patio has sides of 6 m. The distance from the center to the middle of each side is approximately 5.2 m. Use 5.2 m to estimate its area by splitting it into 6 triangles.',answer:93.6,unit:'m²',shape:'text',visual:'6 × (6 × 5.2 ÷ 2)',steps:['Draw lines from the center to each corner: six identical triangles.','Each triangle: base 6, height 5.2. Area = 6 × 5.2 ÷ 2 = 15.6 m².','6 × 15.6 = 93.6 m².']},
// --- Coordinate plane ---
{title:'Map the playground',text:'On a coordinate grid, a rectangle has corners at (1, 2), (7, 2), (7, 6), and (1, 6). Each unit is 1 meter. What is its area?',answer:24,unit:'m²',shape:'text',visual:'(7 − 1) × (6 − 2)',steps:['Find side lengths by subtracting coordinates. Points with the same y share a horizontal side.','Length: 7 − 1 = 6. Width: 6 − 2 = 4.','6 × 4 = 24 m².']},
{title:'Triangle on the grid',text:'A triangle has vertices at (0, 0), (8, 0), and (3, 5). What is its area in square units?',answer:20,unit:'units²',shape:'text',visual:'8 × 5 ÷ 2',steps:['The side from (0, 0) to (8, 0) lies on the x-axis. Its length is 8. That is the base.','The third point is 5 units above the base, so the height is 5.','8 × 5 ÷ 2 = 20 square units.']},
{title:'The square on the grid',text:'A square has vertices at (2, 1), (6, 1), (6, 5), and (2, 5). What is its area?',answer:16,unit:'units²',shape:'text',visual:'(6 − 2)²',steps:['Subtract x-coordinates to find a side: 6 − 2 = 4.','Check with y-coordinates: 5 − 1 = 4. It really is a square.','4 × 4 = 16 square units.']},
// --- Scaling and units ---
{title:'Double trouble',text:'A rectangle is 5 cm by 3 cm. You double both the length and the width. What is the new area?',answer:60,unit:'cm²',shape:'rectangle',a:10,b:6,steps:['Original area: 5 × 3 = 15 cm².','Doubling both sides: 10 × 6.','10 × 6 = 60 cm². Doubling both sides makes the area 4 times bigger, not 2 times.']},
{title:'Switching units',text:'A poster is 2 m by 1.5 m. What is its area in square centimeters?',answer:30000,unit:'cm²',shape:'rectangle',a:200,b:150,steps:['Convert each side to centimeters first: 2 m = 200 cm and 1.5 m = 150 cm.','Then multiply: 200 × 150.','200 × 150 = 30,000 cm². (Notice 3 m² × 10,000 = 30,000. There are 10,000 cm² in 1 m².)']},
// --- Surface area from nets (6.G.A.4) ---
{title:'Unfold the cube',text:'A cube-shaped gift box has edges of 3 cm. If you unfold it into a net, what is the total area of all its faces?',answer:54,unit:'cm²',shape:'text',visual:'6 × (3 × 3)',steps:['A cube net shows 6 identical squares.','Each square: 3 × 3 = 9 cm².','6 × 9 = 54 cm². This is the surface area.']},
{title:'Wrap the box',text:'A rectangular box is 4 in long, 3 in wide, and 2 in tall. How much paper covers all six faces exactly?',answer:52,unit:'in²',shape:'text',visual:'2 × (12 + 8 + 6)',steps:['The net has three pairs of matching rectangles: top/bottom, front/back, left/right.','Top: 4 × 3 = 12. Front: 4 × 2 = 8. Side: 3 × 2 = 6. Each appears twice.','2 × (12 + 8 + 6) = 2 × 26 = 52 in².']}
],detectives:[
{text:'You want enough tiles to cover a rectangular floor. What should you find?',options:['Area','Perimeter','Volume'],correct:0,why:'Tiles cover the inside surface. Area measures that coverage in square units.'},
{text:'Ribbon goes once around the edge of a picture frame. What should you find?',options:['Area','Perimeter','Volume'],correct:1,why:'The ribbon follows the boundary. Perimeter measures distance around, in length units.'},
{text:'How much water can a fish tank hold?',options:['Area','Perimeter','Volume'],correct:2,why:'Water fills three-dimensional space. Volume measures capacity, rather than a flat surface.'},
{text:'A garden has area 35 m² and length 7 m. You need its width. Which plan works?',options:['Multiply 35 by 7','Divide 35 by 7','Add 35 and 7'],correct:1,why:'The relationship is 35 = 7 × width. Divide to find the missing factor. “Area” in the story does not always mean multiply the given numbers.'},
{text:'A triangular sign has base 12 cm, perpendicular height 5 cm, and a slanted side 8 cm. Which measurements find its area?',options:['12 and 8','5 and 8','12 and 5'],correct:2,why:'Use the base and perpendicular height: 12 × 5 ÷ 2. The slanted side is extra information.'},
{text:'A right triangle has legs 6 and 8 and a longest side of 10. Which two lengths are the base and height?',options:['6 and 8','8 and 10','6 and 10'],correct:0,why:'The two legs meet at the right angle, so each is perpendicular to the other. Use 6 × 8 ÷ 2 = 24.'},
{text:'A trapezoid has bases 5 and 11 and height 4. Which expression gives its area?',options:['5 × 11 × 4','(5 + 11) ÷ 2 × 4','(5 + 11) × 4'],correct:1,why:'Average the two parallel bases, then multiply by the height. Multiplying the bases together makes no sense for a trapezoid.'},
{text:'A shape looks like a rectangle with a square bite taken out of one corner. What is the fastest plan?',options:['Big rectangle minus the bite','Add all the side lengths','Multiply every number given'],correct:0,why:'Composite figures can be built by adding pieces or subtracting a missing piece. Subtracting the bite is the quickest here.'},
{text:'A rectangle has corners at (2, 3) and (9, 3) on the same side. How long is that side?',options:['9 + 2 = 11','9 − 2 = 7','9 × 2 = 18'],correct:1,why:'Points with the same y-coordinate lie on a horizontal line. The distance between them is the difference of their x-coordinates.'},
{text:'You triple both side lengths of a square. What happens to its area?',options:['It triples','It becomes 6 times bigger','It becomes 9 times bigger'],correct:2,why:'Area = side × side. If each side is 3 times longer, the area is 3 × 3 = 9 times larger.'},
{text:'A rectangle is 3 m by 2 m. Which unit belongs on the area?',options:['m','m²','m³'],correct:1,why:'Area counts unit squares, so it uses square units. Plain meters measure length; cubic meters measure volume.'},
{text:'A parallelogram has a base of 10 cm, a slanted side of 6 cm, and a perpendicular height of 5 cm. What is its area?',options:['60 cm²','50 cm²','30 cm²'],correct:1,why:'Area = base × perpendicular height = 10 × 5 = 50. The slanted side is not the height.'},
{text:'How much wrapping paper covers a box exactly? What should you find?',options:['Volume','Surface area','Perimeter'],correct:1,why:'Paper covers the faces of the box. Surface area is the total area of all faces, found from the net.'},
{text:'A rectangle has sides 2½ ft and 1⅓ ft. What is the best first move?',options:['Round to 3 and 1','Rewrite as 5/2 and 4/3','Add the two numbers'],correct:1,why:'The area formula still works with fractions. Convert to improper fractions and multiply: 5/2 × 4/3 = 20/6 = 3⅓ ft².'},
{text:'A rhombus has diagonals 8 and 6. Which finds its area?',options:['8 × 6','8 × 6 ÷ 2','(8 + 6) ÷ 2'],correct:1,why:'Perpendicular diagonals cut the rhombus into four right triangles that fill half of an 8 × 6 rectangle.'}
],cards:[
{prompt:'How do you find the area of a rectangle?',formula:'A = length × width',why:'Think of rows of unit squares. The number in each row × the number of rows gives the total.',example:'8 cm × 5 cm = 40 cm²'},
{prompt:'How do you find the area of a triangle?',formula:'A = base × height ÷ 2',why:'Two matching triangles make a parallelogram. Use a height that meets the base at a right angle.',example:'10 cm × 6 cm ÷ 2 = 30 cm²'},
{prompt:'How do you find the area of a parallelogram?',formula:'A = base × height',why:'Move a triangular end to the other side to form a rectangle. Height is the perpendicular distance between the bases.',example:'9 cm × 4 cm = 36 cm²'},
{prompt:'How do you find the area of a square?',formula:'A = side × side = s²',why:'A square has equal length and width. Squared means multiply the side by itself, not by two.',example:'6 ft × 6 ft = 36 ft²'},
{prompt:'How do you find the area of a trapezoid?',formula:'A = (b₁ + b₂) ÷ 2 × h',why:'Average the two parallel bases to get a rectangle with the same area. Or split it into a rectangle and triangles.',example:'(8 + 12) ÷ 2 × 5 = 50 ft²'},
{prompt:'How do you find the area of a rhombus or kite?',formula:'A = d₁ × d₂ ÷ 2',why:'The diagonals are perpendicular, so they cut the shape into right triangles that fill half of a d₁ × d₂ rectangle.',example:'10 cm × 6 cm ÷ 2 = 30 cm²'},
{prompt:'How do you find the area of a composite figure?',formula:'Add pieces, or subtract a hole',why:'Cut the shape into rectangles and triangles you know. Or start with a bigger shape and subtract what is missing.',example:'L-shape: 10 × 8 − 4 × 3 = 68 m²'},
{prompt:'How do you find a missing side when you know the area?',formula:'Divide the area by the known measurement',why:'Area = length × width is a multiplication fact. Undo it with division. For triangles, double the area first.',example:'48 = 8 × w → w = 48 ÷ 8 = 6 m'},
{prompt:'How do you find horizontal or vertical lengths on a coordinate plane?',formula:'Subtract the coordinates that differ',why:'Points on the same horizontal line share a y-value, so subtract x-values. Points on the same vertical line share an x-value, so subtract y-values.',example:'(1, 2) to (7, 2): 7 − 1 = 6 units'},
{prompt:'What happens to area when you scale all sides?',formula:'Scale by k → area × k²',why:'Both length and width get multiplied by k, so the area gets multiplied by k twice.',example:'Double sides → 4× area; triple → 9× area'},
{prompt:'How do you find surface area from a net?',formula:'Add the area of every face',why:'A net is the 3D shape unfolded flat. Find each face as a rectangle or triangle, then add them all.',example:'Cube, edge 3: 6 × 9 = 54 cm²'},
{prompt:'How do you handle fractional side lengths?',formula:'Same formula, fraction multiplication',why:'Convert mixed numbers to improper fractions, multiply numerators and denominators, then simplify.',example:'4½ × 2⅔ = 9/2 × 8/3 = 12 ft²'}]},
{id:'fractions',name:'Fractions',subtitle:'Make equal parts make sense. Multiply, divide, and reason with any fraction.',problems:[
// --- Adding and subtracting ---
{title:'Share the trail mix',text:'You mix 1/4 cup of raisins with 2/4 cup of nuts. How many cups of trail mix is that?',answer:.75,unit:'cup',shape:'text',visual:'¼ + ²⁄₄',steps:['We are combining amounts, so add.','Both amounts use fourths. Add the numerators and keep the denominator: (1 + 2)/4.','3/4 cup. You can enter 3/4 or 0.75.']},
{title:'The leftover ribbon',text:'You have 5/6 meter of ribbon and use 1/3 meter. How much remains?',answer:.5,unit:'m',shape:'text',visual:'⁵⁄₆ − ⅓',steps:['Remaining amount means subtract the part used from what you had.','Make equal-sized parts: 1/3 = 2/6. Then 5/6 − 2/6 = 3/6.','Simplify 3/6 to 1/2 meter.']},
{title:'Two hikes',text:'On Saturday you hike 2¼ miles. On Sunday you hike 1½ miles. How far did you hike in all?',answer:3.75,unit:'mi',shape:'text',visual:'2¼ + 1½',steps:['Combining distances, so add the mixed numbers.','Whole parts: 2 + 1 = 3. Fraction parts: 1/4 + 2/4 = 3/4.','3 + 3/4 = 3¾ miles, or 3.75.']},
{title:'Borrow a whole',text:'A board is 5¼ feet long. You cut off 2¾ feet. How much is left?',answer:2.5,unit:'ft',shape:'text',visual:'5¼ − 2¾',steps:['Subtract the piece cut off. But 1/4 is smaller than 3/4, so regroup.','5¼ = 4 + 5/4. Now subtract: 4 − 2 = 2 and 5/4 − 3/4 = 2/4.','2 + 2/4 = 2½ feet, or 2.5.']},
{title:'Unlike denominators',text:'A recipe calls for 2/3 cup of sugar and 1/6 cup of honey. How much sweetener is that altogether? Enter a fraction or round to 4 decimal places.',answer:5/6,decimalPlaces:4,unit:'cup',shape:'text',visual:'⅔ + ⅙',steps:['Add, but the parts are different sizes. Find a common denominator: 6.','2/3 = 4/6. Then 4/6 + 1/6 = 5/6.','5/6 cup. As a decimal that is about 0.8333.']},
// --- Multiplying ---
{title:'Half of a recipe',text:'A recipe needs 3/4 cup of milk. You make half the recipe. How much milk do you need?',answer:.375,unit:'cup',shape:'text',visual:'½ × ¾',steps:['We need half of an amount. Multiply by 1/2.','Multiply numerators and denominators: (1 × 3)/(2 × 4).','3/8 cup, or 0.375 cup.']},
{title:'Fraction of a class',text:'There are 35 students in a class. 2/5 of them ride the bus. How many students ride the bus?',answer:14,unit:'students',shape:'text',visual:'⅖ × 35',steps:['“Of” a whole number means multiply.','2/5 × 35 = (2 × 35)/5 = 70/5.','70 ÷ 5 = 14 students. Or: 35 ÷ 5 = 7 per fifth, and 2 × 7 = 14.']},
{title:'Mixed number multiply',text:'A rectangle is 1½ m by 2⅔ m. What is its area?',answer:4,unit:'m²',shape:'text',visual:'1½ × 2⅔',steps:['Area = length × width. Convert the mixed numbers first.','1½ = 3/2 and 2⅔ = 8/3. Multiply: (3 × 8)/(2 × 3) = 24/6.','24/6 = 4 m².']},
{title:'Flour left, then used',text:'You have 3/4 pound of flour. You use 2/3 of it for bread. How much flour did the bread use?',answer:.5,unit:'lb',shape:'text',visual:'⅔ × ¾',steps:['We want 2/3 of 3/4. That is multiplication.','(2 × 3)/(3 × 4) = 6/12.','Simplify: 6/12 = 1/2 pound.']},
{title:'Tiny tile',text:'A tile is 2/3 ft wide and 3/4 ft tall. What is its area?',answer:.5,unit:'ft²',shape:'text',visual:'⅔ × ¾',steps:['Area = width × height, even with fractions.','(2 × 3)/(3 × 4) = 6/12.','6/12 = 1/2 ft².']},
// --- Dividing (the 6th-grade core) ---
{title:'Little scoops',text:'You have 3/4 cup of oats. Each scoop holds 1/8 cup. How many full scoops can you fill?',answer:6,unit:'scoops',shape:'text',visual:'¾ ÷ ⅛',steps:['We want the number of equal groups. Divide total oats by the scoop size.','3/4 is 6/8. There are six eighths in that amount.','You can fill 6 scoops.']},
{title:'Flip and multiply',text:'A ribbon is 2/3 yard long. You cut it into pieces that are each 1/6 yard. How many pieces do you get?',answer:4,unit:'pieces',shape:'text',visual:'⅔ ÷ ⅙',steps:['How many 1/6-size groups fit in 2/3? Divide.','Dividing by a fraction is the same as multiplying by its reciprocal: 2/3 × 6/1 = 12/3.','12/3 = 4 pieces. Check: 2/3 = 4/6, and there are four sixths in 4/6.']},
{title:'Whole number divided by a fraction',text:'You have 5 cups of rice. One batch of the recipe uses 2/3 cup. How many batches can you make?',answer:7.5,unit:'batches',shape:'text',visual:'5 ÷ ⅔',steps:['How many 2/3-cup groups fit in 5 cups? Divide 5 by 2/3.','5 ÷ 2/3 = 5 × 3/2 = 15/2.','15/2 = 7½ batches. Seven full batches, plus half of another.']},
{title:'Fraction divided by a whole number',text:'You share 3/4 of a pizza equally among 3 friends. What fraction of the whole pizza does each friend get?',answer:.25,unit:'pizza',shape:'text',visual:'¾ ÷ 3',steps:['Splitting into equal shares: divide 3/4 by 3.','3/4 ÷ 3 = 3/4 × 1/3 = 3/12.','3/12 = 1/4 of the pizza each.']},
{title:'Dividing mixed numbers',text:'A trail is 4½ miles long. Rest stops are every 3/4 mile. How many stretches of 3/4 mile are on the trail?',answer:6,unit:'stretches',shape:'text',visual:'4½ ÷ ¾',steps:['Convert the mixed number: 4½ = 9/2.','9/2 ÷ 3/4 = 9/2 × 4/3 = 36/6.','36/6 = 6 stretches.']},
{title:'Scarves from a bolt',text:'You have 7½ yards of fabric. Each scarf needs 5/8 yard. How many scarves can you make?',answer:12,unit:'scarves',shape:'text',visual:'7½ ÷ ⅝',steps:['Equal groups of 5/8 out of 7½: divide.','7½ = 15/2. Then 15/2 × 8/5 = 120/10.','120/10 = 12 scarves.']},
{title:'Full pieces only',text:'A rope is 6 meters long. You cut pieces that are each 4/5 meter. How many full pieces can you cut?',answer:7,unit:'pieces',shape:'text',visual:'6 ÷ ⅘',steps:['Divide: 6 ÷ 4/5 = 6 × 5/4 = 30/4.','30/4 = 7½. The 1/2 means half of a piece, which is not a full piece.','7 full pieces, with 2/5 meter of rope left over.']},
{title:'Servings in a bag',text:'A bag holds 5/6 pound of almonds. One serving is 1/12 pound. How many servings are in the bag?',answer:10,unit:'servings',shape:'text',visual:'⅚ ÷ ¹⁄₁₂',steps:['Number of equal groups: divide the total by the serving size.','5/6 ÷ 1/12 = 5/6 × 12/1 = 60/6.','60/6 = 10 servings.']},
{title:'Split it in half',text:'You have 2½ liters of lemonade and pour it equally into 5 bottles. How much goes in each bottle?',answer:.5,unit:'L',shape:'text',visual:'2½ ÷ 5',steps:['Equal shares: divide the total by the number of bottles.','2½ = 5/2. Then 5/2 ÷ 5 = 5/2 × 1/5 = 5/10.','5/10 = 1/2 liter each.']},
// --- Unit rates with fractions (6.RP) ---
{title:'Speed walk',text:'You walk 1/2 mile in 1/4 hour. How many miles do you walk in 1 hour at that pace?',answer:2,unit:'mph',shape:'text',visual:'½ ÷ ¼',steps:['A rate per hour means miles ÷ hours.','1/2 ÷ 1/4 = 1/2 × 4/1 = 4/2.','4/2 = 2 miles per hour.']},
{title:'Paint per wall',text:'You use 3/4 gallon of paint to cover 2/3 of a wall. How many gallons cover one whole wall?',answer:1.125,unit:'gal',shape:'text',visual:'¾ ÷ ⅔',steps:['Gallons per wall means gallons ÷ walls.','3/4 ÷ 2/3 = 3/4 × 3/2 = 9/8.','9/8 = 1⅛ gallons, or 1.125.']},
// --- Fractions, decimals, percents ---
{title:'Fraction to decimal',text:'A race is 7/8 of a mile. Write that distance as a decimal.',answer:.875,unit:'mi',shape:'text',visual:'7 ÷ 8',steps:['A fraction is a division: 7/8 means 7 ÷ 8.','Divide: 8 goes into 7.000 → 0.875.','7/8 = 0.875 mile.']},
{title:'Out of one hundred',text:'You answered 3/20 of a quiz incorrectly. What percent is that?',answer:15,unit:'%',shape:'text',visual:'³⁄₂₀ = ?⁄₁₀₀',steps:['Percent means out of 100. Scale the fraction to a denominator of 100.','20 × 5 = 100, so multiply top and bottom by 5: 15/100.','15/100 = 15%.']},
{title:'Decimal to fraction',text:'A bolt is 0.625 inch thick. Write that as a fraction in simplest form.',answer:.625,unit:'in',shape:'text',visual:'0.625 = ⁶²⁵⁄₁₀₀₀',steps:['0.625 has three decimal places: 625/1000.','Divide top and bottom by 125.','625/1000 = 5/8 inch. Enter 5/8 or 0.625.']},
// --- Multi-step ---
{title:'Two-step lemonade',text:'You make 3¾ liters of lemonade and drink 1¼ liters. You pour the rest equally into 5 cups. How much is in each cup?',answer:.5,unit:'L',shape:'text',visual:'(3¾ − 1¼) ÷ 5',steps:['First find what is left: 3¾ − 1¼ = 2½ liters.','Then share it: 2½ ÷ 5 = 5/2 × 1/5 = 5/10.','5/10 = 1/2 liter in each cup.']},
{title:'Garden rows',text:'A garden bed is 2/3 the length of a 9-foot fence. How many 1/2-foot plants fit in a row along the bed?',answer:12,unit:'plants',shape:'text',visual:'(⅔ × 9) ÷ ½',steps:['First find the bed length: 2/3 × 9 = 6 feet.','Then count 1/2-foot groups: 6 ÷ 1/2 = 6 × 2 = 12.','12 plants fit.']}
],detectives:[
{text:'You combine 1/2 liter of juice and 1/4 liter of water. Which operation finds the total?',options:['Add','Multiply','Divide'],correct:0,why:'You are putting two amounts together. Use a common denominator, then add.'},
{text:'You need one third of a 3/4-cup serving. Which operation finds the amount?',options:['Subtract','Multiply','Divide'],correct:1,why:'You are scaling an amount to one third of its size: 1/3 × 3/4.'},
{text:'How many 1/4-meter pieces fit in 2 meters of string?',options:['Add','Subtract','Divide'],correct:2,why:'The question asks how many equal groups fit: 2 ÷ 1/4 = 8.'},
{text:'“Each bag holds 2/3 pound. How many bags for 6 pounds?” Which operation?',options:['6 × 2/3','6 ÷ 2/3','6 − 2/3'],correct:1,why:'“How many groups of a size” signals division. 6 ÷ 2/3 = 9 bags.'},
{text:'Before you divide 3½ ÷ 1¼, what should you do first?',options:['Round both to whole numbers','Convert both to improper fractions','Find a common denominator'],correct:1,why:'Rewrite as 7/2 ÷ 5/4, then multiply by the reciprocal: 7/2 × 4/5 = 28/10 = 2⅘.'},
{text:'What is the reciprocal of 2½?',options:['5/2','2/5','1/2'],correct:1,why:'2½ = 5/2. Flip it: 2/5. Do not flip the mixed number without converting first.'},
{text:'Is 8 ÷ 1/2 bigger or smaller than 8?',options:['Bigger','Smaller','The same'],correct:0,why:'Dividing by a number less than 1 asks how many small pieces fit. Sixteen halves fit in 8, so the answer grows.'},
{text:'To add 1/3 + 1/4, which common denominator is the most efficient?',options:['7','12','24'],correct:1,why:'12 is the least common multiple of 3 and 4: 4/12 + 3/12 = 7/12. Never add the denominators.'},
{text:'You ran 3/4 mile in 1/6 hour. Which finds your speed in miles per hour?',options:['3/4 × 1/6','1/6 ÷ 3/4','3/4 ÷ 1/6'],correct:2,why:'Miles per hour means miles ÷ hours: 3/4 ÷ 1/6 = 3/4 × 6 = 4½ mph.'},
{text:'Estimate 7/8 + 11/12.',options:['About 1','About 2','About 3'],correct:1,why:'Each fraction is close to 1, so the sum is close to 2. Estimating helps you catch mistakes.'},
{text:'You divide 9 ÷ 4/5 and get 11¼. You need full boxes. How many full boxes?',options:['11','12','11.25'],correct:0,why:'The ¼ means part of a box. Only 11 boxes are complete. Read what the question asks.'},
{text:'Which is larger: 5/8 or 0.6?',options:['5/8','0.6','They are equal'],correct:0,why:'5/8 = 0.625, which is greater than 0.600. Converting to decimals makes fractions easy to compare.'},
{text:'Half of a number is 3/4. Which finds the number?',options:['3/4 × 1/2','3/4 ÷ 1/2','3/4 − 1/2'],correct:1,why:'Undo “half of” with division: 3/4 ÷ 1/2 = 3/4 × 2 = 1½.'},
{text:'A recipe uses 2/3 cup of oil. You triple it. What is the best plan?',options:['3 × 2/3','2/3 ÷ 3','2/3 + 3'],correct:0,why:'Tripling means multiplying by 3: 3 × 2/3 = 6/3 = 2 cups.'}
],cards:[
{prompt:'How do you add fractions with different denominators?',formula:'Same-sized parts, then add',why:'Find a common denominator. Rewrite both fractions as equivalent fractions, then add their numerators.',example:'1/2 + 1/4 = 2/4 + 1/4 = 3/4'},
{prompt:'How do you subtract mixed numbers when the fraction is too small?',formula:'Regroup one whole into the fraction',why:'Borrow 1 from the whole number and add it to the fraction part, then subtract as usual.',example:'5¼ − 2¾ = 4⁵⁄₄ − 2¾ = 2½'},
{prompt:'How do you multiply two fractions?',formula:'a/b × c/d = ac/bd',why:'Multiply the numerators and multiply the denominators. Denominators cannot be zero. Simplify if possible.',example:'1/2 × 3/4 = 3/8'},
{prompt:'How do you find a fraction of a whole number?',formula:'a/b × n = (a × n)/b',why:'“Of” means multiply. Or divide the whole number by the denominator first, then multiply by the numerator.',example:'2/5 × 35 = 70/5 = 14'},
{prompt:'How do you divide by a nonzero fraction?',formula:'a/b ÷ c/d = a/b × d/c',why:'Multiply by the reciprocal of the divisor. Think: how many groups of that size fit? All denominators and the divisor must be nonzero.',example:'3/4 ÷ 1/8 = 3/4 × 8/1 = 6'},
{prompt:'How do you convert a mixed number to an improper fraction?',formula:'whole × denominator + numerator',why:'Each whole is one full set of parts. Count all the parts, then keep the same denominator.',example:'4½ = (4 × 2 + 1)/2 = 9/2'},
{prompt:'How do you multiply or divide mixed numbers?',formula:'Convert first, then multiply or flip',why:'Mixed numbers hide a plus sign. Turn them into improper fractions so the rules for fractions apply.',example:'1½ × 2⅔ = 3/2 × 8/3 = 4'},
{prompt:'How do you find a unit rate with fractions?',formula:'rate = amount ÷ time (or per 1 unit)',why:'“Per hour” means for 1 hour. Divide the distance by the fraction of an hour, using the reciprocal.',example:'1/2 mi ÷ 1/4 hr = 2 mph'},
{prompt:'How do you turn a fraction into a decimal?',formula:'Divide numerator by denominator',why:'A fraction bar is a division sign. Long division gives the decimal.',example:'7/8 = 7 ÷ 8 = 0.875'},
{prompt:'How do you turn a fraction into a percent?',formula:'Scale to a denominator of 100',why:'Percent means per hundred. Multiply top and bottom by the same number, or convert to a decimal and multiply by 100.',example:'3/20 = 15/100 = 15%'},
{prompt:'Why does dividing a positive number by a positive fraction less than 1 make the answer bigger?',formula:'n ÷ (small piece) = many pieces',why:'Division asks how many pieces fit. Small pieces fit many times, so the quotient can be larger than what you started with.',example:'8 ÷ 1/2 = 16'},
{prompt:'How do you check a fraction answer?',formula:'Estimate, then multiply back',why:'Round fractions to 0, ½, or 1 to estimate. For division, multiply the quotient by the divisor to get the dividend.',example:'6 × 1/8 = 6/8 = 3/4 ✓'}]}
];
