import type { Topic } from './types';
export const CURRICULUM: Topic[] = [
{id:'area',name:'Area',subtitle:'Explore area. See the space. Solve the mystery.',problems:[
// --- Warm-up: the four basic shapes ---
{title:'A space for your ideas',text:'Your rectangular art board is 8 cm long and 5 cm wide. How much space is there for your artwork?',answer:40,unit:'cm²',shape:'rectangle',a:8,b:5,steps:['Find the space inside the board. That means area, measured in square units.','A rectangle has rows of equal squares. Use area = length × width.','Substitute: 8 × 5 = 40. The area is 40 cm².']},
{title:'Build a reading nook',text:'A square rug has sides of 6 feet. What area of the floor will it cover?',answer:36,unit:'ft²',shape:'square',a:6,b:6,steps:['We want the floor covered, so find area.','A square is a rectangle with equal sides: area = side × side.','6 × 6 = 36 square feet.']},
{title:'Design a pennant',text:'A triangular pennant has a base of 10 cm and a perpendicular height of 6 cm. What is its area?',answer:30,unit:'cm²',shape:'triangle',a:10,b:6,steps:['Find the space inside the triangle. The height is perpendicular to the base.','A triangle takes up half of a matching parallelogram: area = base × height ÷ 2.','10 × 6 ÷ 2 = 30 cm².']},
{title:'A slanted splash of color',text:'A parallelogram sticker has a base of 9 cm and a perpendicular height of 4 cm. Find its area.',answer:36,unit:'cm²',shape:'parallelogram',a:9,b:4,steps:['Use the perpendicular height, not the slanted side.','Sliding a triangular piece from one side to the other makes a rectangle. Area = base × height.','9 × 4 = 36 cm².']},
// --- Missing measurements ---
{title:'The garden mystery',text:'A rectangular garden has an area of 48 m² and a length of 8 m. How wide is it?',answer:6,unit:'m',shape:'rectangle',a:8,b:'?',steps:['We already know the area. The missing measurement is width, in meters.','Area = length × width, so 48 = 8 × width. Undo multiplication with division.','48 ÷ 8 = 6. The width is 6 m.']},
{title:'The missing height',text:'A triangular flag has an area of 36 in² and a base of 9 in. What is its perpendicular height?',answer:8,unit:'in',shape:'triangle',a:9,b:'?',steps:['We know the area and base. We need the height.','Area = base × height ÷ 2, so 36 = 9 × height ÷ 2. Double both sides first: 72 = 9 × height.','72 ÷ 9 = 8. The height is 8 inches.']},
{title:'A parallelogram puzzle',text:'A parallelogram has an area of 52.5 cm² and a perpendicular height of 7 cm. How long is its base?',answer:7.5,unit:'cm',shape:'parallelogram',a:'?',b:7,steps:['Area = base × height. We know area and height.','52.5 = base × 7. Divide to find the missing factor.','52.5 ÷ 7 = 7.5 cm.']},
// --- Decimals and fractions as side lengths ---
{title:'A tiny studio',text:'A rectangular tabletop is 2.5 m long and 1.2 m wide. How much surface area does it have?',answer:3,unit:'m²',shape:'rectangle',a:2.5,b:1.2,steps:['Surface area here means the flat top, a rectangle.','Use length × width: 2.5 × 1.2.','25 × 12 = 300. Put back two decimal places: 3.00 m².']},
{title:'Fractional floor plan',text:'A closet floor is 4½ ft long and 2⅔ ft wide. What is its area?',answer:12,unit:'ft²',shape:'rectangle',a:4.5,b:'2⅔',steps:['Area = length × width, even when the sides are mixed numbers.','Rewrite as improper fractions: 4½ = 9/2 and 2⅔ = 8/3.','9/2 × 8/3 = 72/6 = 12 ft².']},
{title:'One last triangle',text:'A triangular sail has a base of 7 m and a perpendicular height of 5 m. Find its area.',answer:17.5,unit:'m²',shape:'triangle',a:7,b:5,steps:['Find area using the base and perpendicular height.','Area = base × height ÷ 2.','7 × 5 = 35. Half of 35 is 17.5 m².']},
{title:'Half-inch squares',text:'A sticky note is 3½ in by 3½ in. What is its area?',answer:12.25,unit:'in²',shape:'square',a:3.5,b:3.5,steps:['A square: area = side × side.','3½ = 7/2. So 7/2 × 7/2 = 49/4.','49/4 = 12¼ = 12.25 in².']},
// --- Right triangles and rectangles ---
{title:'Cut on the diagonal',text:'A rectangular sandwich is 10 cm by 6 cm. You cut it corner to corner. What is the area of one triangular half?',answer:30,unit:'cm²',shape:'triangle',a:10,b:6,steps:['The diagonal splits the rectangle into two equal right triangles.','Rectangle area: 10 × 6 = 60 cm². Each triangle is half of that.','60 ÷ 2 = 30 cm². Same as base × height ÷ 2 with the two legs.']},
// --- Trapezoids, rhombuses, kites ---
{title:'The trapezoid table',text:'A trapezoid tabletop has parallel sides of 8 ft and 12 ft, and the distance between them is 5 ft. Find its area.',answer:50,unit:'ft²',shape:'text',visual:'(8 + 12) ÷ 2 × 5',steps:['A trapezoid has two parallel bases. Average them to make an equal-area rectangle.','(8 + 12) ÷ 2 = 10. That is the average base.','10 × 5 = 50 ft².']},
{title:'Splitting the trapezoid',text:'A right trapezoid has bases 6.5 m and 9.5 m and height 4 m. Find its area by splitting it into a rectangle and a triangle.',answer:32,unit:'m²',shape:'text',visual:'26 + 6',steps:['Decompose: a 6.5 × 4 rectangle plus a triangle with base 9.5 − 6.5 = 3 and height 4.','Rectangle: 6.5 × 4 = 26. Triangle: 3 × 4 ÷ 2 = 6.','26 + 6 = 32 m². Check: (6.5 + 9.5) ÷ 2 × 4 = 32. Both ways agree.']},
{title:'A diamond in the rough',text:'A rhombus-shaped tile has diagonals of 10 cm and 6 cm. What is its area?',answer:30,unit:'cm²',shape:'text',visual:'10 × 6 ÷ 2',steps:['The diagonals cross at right angles and cut the rhombus into four right triangles.','Those four triangles fill exactly half of a 10 × 6 rectangle.','10 × 6 ÷ 2 = 30 cm².']},
{title:'Fly the kite',text:'A kite has diagonals of 14 in and 9 in. Find its area.',answer:63,unit:'in²',shape:'text',visual:'14 × 9 ÷ 2',steps:['A kite works like a rhombus: its diagonals are perpendicular.','Area = diagonal × diagonal ÷ 2.','14 × 9 = 126. Half is 63 in².']},
// --- Composite figures ---
{title:'Room for two',text:'A craft mat is made from two non-overlapping rectangles. One is 6 cm by 4 cm; the other is 3 cm by 2 cm. What is their total area?',answer:30,unit:'cm²',shape:'text',visual:'24 + 6',steps:['The two pieces do not overlap, so we can add their areas.','First rectangle: 6 × 4 = 24 cm². Second rectangle: 3 × 2 = 6 cm².','24 + 6 = 30 cm² in all.']},
{title:'The L-shaped room',text:'An L-shaped room fits inside a 10 m by 8 m rectangle, but a 4 m by 3 m corner is missing. What is the floor area?',answer:68,unit:'m²',shape:'text',visual:'80 − 12',steps:['Start with the big rectangle, then subtract the missing corner.','Big rectangle: 10 × 8 = 80 m². Missing corner: 4 × 3 = 12 m².','80 − 12 = 68 m².']},
{title:'House shape',text:'A house-shaped sign is a 12 cm by 5 cm rectangle with a triangle roof on top. The roof has base 12 cm and height 4 cm. Find the total area.',answer:84,unit:'cm²',shape:'text',visual:'60 + 24',steps:['Decompose into a rectangle and a triangle that share the 12 cm edge.','Rectangle: 12 × 5 = 60. Triangle: 12 × 4 ÷ 2 = 24.','60 + 24 = 84 cm².']},
{title:'Paint the wall',text:'A wall is 12 ft wide and 8 ft tall. It has one window that is 3 ft by 4 ft. How much wall needs paint?',answer:84,unit:'ft²',shape:'text',visual:'96 − 12',steps:['Paint covers the wall but not the window. Subtract the window area.','Wall: 12 × 8 = 96 ft². Window: 3 × 4 = 12 ft².','96 − 12 = 84 ft².']},
{title:'The hexagon patio',text:'A regular hexagon patio has sides of 6 m. The distance from the center to the middle of each side is approximately 5.2 m. Use 5.2 m to estimate its area by splitting it into 6 triangles.',answer:93.6,unit:'m²',shape:'text',visual:'6 × (6 × 5.2 ÷ 2)',steps:['Draw lines from the center to each corner: six identical triangles.','Each triangle: base 6, height 5.2. Area = 6 × 5.2 ÷ 2 = 15.6 m².','6 × 15.6 = 93.6 m².']},
// --- Coordinate plane ---
{title:'Map the playground',text:'On a coordinate grid, a rectangle has corners at (1, 2), (7, 2), (7, 6), and (1, 6). Each unit is 1 meter. What is its area?',answer:24,unit:'m²',shape:'text',visual:'(7 − 1) × (6 − 2)',steps:['Find side lengths by subtracting coordinates. Points with the same y share a horizontal side.','Length: 7 − 1 = 6. Width: 6 − 2 = 4.','6 × 4 = 24 m².']},
{title:'Triangle on the grid',text:'A triangle has vertices at (0, 0), (8, 0), and (3, 5). What is its area in square units?',answer:20,unit:'units²',shape:'text',visual:'8 × 5 ÷ 2',steps:['The side from (0, 0) to (8, 0) lies on the x-axis. Its length is 8. That is the base.','The third point is 5 units above the base, so the height is 5.','8 × 5 ÷ 2 = 20 square units.']},
{title:'The square on the grid',text:'A square has vertices at (2, 1), (6, 1), (6, 5), and (2, 5). What is its area?',answer:16,unit:'units²',shape:'text',visual:'(6 − 2)²',steps:['Subtract x-coordinates to find a side: 6 − 2 = 4.','Check with y-coordinates: 5 − 1 = 4. It really is a square.','4 × 4 = 16 square units.']},
// --- Scaling and units ---
{title:'Double trouble',text:'A rectangle is 5 cm by 3 cm. You double both the length and the width. What is the new area?',answer:60,unit:'cm²',shape:'rectangle',a:10,b:6,steps:['Original area: 5 × 3 = 15 cm².','Doubling both sides: 10 × 6.','10 × 6 = 60 cm². Doubling both sides makes the area 4 times bigger, not 2 times.']},
{title:'Switching units',text:'A poster is 2 m by 1.5 m. What is its area in square centimeters?',answer:30000,unit:'cm²',shape:'rectangle',a:200,b:150,steps:['Convert each side to centimeters first: 2 m = 200 cm and 1.5 m = 150 cm.','Then multiply: 200 × 150.','200 × 150 = 30,000 cm². (Notice 3 m² × 10,000 = 30,000. There are 10,000 cm² in 1 m².)']},
// --- Surface area from nets (6.G.A.4) ---
{title:'Unfold the cube',text:'A cube-shaped gift box has edges of 3 cm. If you unfold it into a net, what is the total area of all its faces?',answer:54,unit:'cm²',shape:'text',visual:'6 × (3 × 3)',steps:['A cube net shows 6 identical squares.','Each square: 3 × 3 = 9 cm².','6 × 9 = 54 cm². This is the surface area.']},
{title:'Wrap the box',text:'A rectangular box is 4 in long, 3 in wide, and 2 in tall. How much paper covers all six faces exactly?',answer:52,unit:'in²',shape:'text',visual:'2 × (12 + 8 + 6)',steps:['The net has three pairs of matching rectangles: top/bottom, front/back, left/right.','Top: 4 × 3 = 12. Front: 4 × 2 = 8. Side: 3 × 2 = 6. Each appears twice.','2 × (12 + 8 + 6) = 2 × 26 = 52 in².']}
],detectives:[
{text:'You want enough tiles to cover a rectangular floor. What should you find?',options:['Area','Perimeter','Volume'],correct:0,why:'Tiles cover the inside surface. Area measures that coverage in square units.'},
{text:'Ribbon goes once around the edge of a picture frame. What should you find?',options:['Area','Perimeter','Volume'],correct:1,why:'The ribbon follows the boundary. Perimeter measures distance around, in length units.'},
{text:'How much water can a fish tank hold?',options:['Area','Perimeter','Volume'],correct:2,why:'Water fills three-dimensional space. Volume measures capacity, rather than a flat surface.'},
{text:'A garden has area 35 m² and length 7 m. You need its width. Which plan works?',options:['Multiply 35 by 7','Divide 35 by 7','Add 35 and 7'],correct:1,why:'The relationship is 35 = 7 × width. Divide to find the missing factor. “Area” in the story does not always mean multiply the given numbers.'},
{text:'A triangular sign has base 12 cm, perpendicular height 5 cm, and a slanted side 8 cm. Which measurements find its area?',options:['12 and 8','5 and 8','12 and 5'],correct:2,why:'Use the base and perpendicular height: 12 × 5 ÷ 2. The slanted side is extra information.'},
{text:'A right triangle has legs 6 and 8 and a longest side of 10. Which two lengths are the base and height?',options:['6 and 8','8 and 10','6 and 10'],correct:0,why:'The two legs meet at the right angle, so each is perpendicular to the other. Use 6 × 8 ÷ 2 = 24.'},
{text:'A trapezoid has bases 5 and 11 and height 4. Which expression gives its area?',options:['5 × 11 × 4','(5 + 11) ÷ 2 × 4','(5 + 11) × 4'],correct:1,why:'Average the two parallel bases, then multiply by the height. Multiplying the bases together makes no sense for a trapezoid.'},
{text:'A shape looks like a rectangle with a square bite taken out of one corner. What is the fastest plan?',options:['Big rectangle minus the bite','Add all the side lengths','Multiply every number given'],correct:0,why:'Composite figures can be built by adding pieces or subtracting a missing piece. Subtracting the bite is the quickest here.'},
{text:'A rectangle has corners at (2, 3) and (9, 3) on the same side. How long is that side?',options:['9 + 2 = 11','9 − 2 = 7','9 × 2 = 18'],correct:1,why:'Points with the same y-coordinate lie on a horizontal line. The distance between them is the difference of their x-coordinates.'},
{text:'You triple both side lengths of a square. What happens to its area?',options:['It triples','It becomes 6 times bigger','It becomes 9 times bigger'],correct:2,why:'Area = side × side. If each side is 3 times longer, the area is 3 × 3 = 9 times larger.'},
{text:'A rectangle is 3 m by 2 m. Which unit belongs on the area?',options:['m','m²','m³'],correct:1,why:'Area counts unit squares, so it uses square units. Plain meters measure length; cubic meters measure volume.'},
{text:'A parallelogram has a base of 10 cm, a slanted side of 6 cm, and a perpendicular height of 5 cm. What is its area?',options:['60 cm²','50 cm²','30 cm²'],correct:1,why:'Area = base × perpendicular height = 10 × 5 = 50. The slanted side is not the height.'},
{text:'How much wrapping paper covers a box exactly? What should you find?',options:['Volume','Surface area','Perimeter'],correct:1,why:'Paper covers the faces of the box. Surface area is the total area of all faces, found from the net.'},
{text:'A rectangle has sides 2½ ft and 1⅓ ft. What is the best first move?',options:['Round to 3 and 1','Rewrite as 5/2 and 4/3','Add the two numbers'],correct:1,why:'The area formula still works with fractions. Convert to improper fractions and multiply: 5/2 × 4/3 = 20/6 = 3⅓ ft².'},
{text:'A rhombus has diagonals 8 and 6. Which finds its area?',options:['8 × 6','8 × 6 ÷ 2','(8 + 6) ÷ 2'],correct:1,why:'Perpendicular diagonals cut the rhombus into four right triangles that fill half of an 8 × 6 rectangle.'}
],cards:[
{prompt:'How do you find the area of a rectangle?',formula:'A = length × width',why:'Think of rows of unit squares. The number in each row × the number of rows gives the total.',example:'8 cm × 5 cm = 40 cm²'},
{prompt:'How do you find the area of a triangle?',formula:'A = base × height ÷ 2',why:'Two matching triangles make a parallelogram. Use a height that meets the base at a right angle.',example:'10 cm × 6 cm ÷ 2 = 30 cm²'},
{prompt:'How do you find the area of a parallelogram?',formula:'A = base × height',why:'Move a triangular end to the other side to form a rectangle. Height is the perpendicular distance between the bases.',example:'9 cm × 4 cm = 36 cm²'},
{prompt:'How do you find the area of a square?',formula:'A = side × side = s²',why:'A square has equal length and width. Squared means multiply the side by itself, not by two.',example:'6 ft × 6 ft = 36 ft²'},
{prompt:'How do you find the area of a trapezoid?',formula:'A = (b₁ + b₂) ÷ 2 × h',why:'Average the two parallel bases to get a rectangle with the same area. Or split it into a rectangle and triangles.',example:'(8 + 12) ÷ 2 × 5 = 50 ft²'},
{prompt:'How do you find the area of a rhombus or kite?',formula:'A = d₁ × d₂ ÷ 2',why:'The diagonals are perpendicular, so they cut the shape into right triangles that fill half of a d₁ × d₂ rectangle.',example:'10 cm × 6 cm ÷ 2 = 30 cm²'},
{prompt:'How do you find the area of a composite figure?',formula:'Add pieces, or subtract a hole',why:'Cut the shape into rectangles and triangles you know. Or start with a bigger shape and subtract what is missing.',example:'L-shape: 10 × 8 − 4 × 3 = 68 m²'},
{prompt:'How do you find a missing side when you know the area?',formula:'Divide the area by the known measurement',why:'Area = length × width is a multiplication fact. Undo it with division. For triangles, double the area first.',example:'48 = 8 × w → w = 48 ÷ 8 = 6 m'},
{prompt:'How do you find horizontal or vertical lengths on a coordinate plane?',formula:'Subtract the coordinates that differ',why:'Points on the same horizontal line share a y-value, so subtract x-values. Points on the same vertical line share an x-value, so subtract y-values.',example:'(1, 2) to (7, 2): 7 − 1 = 6 units'},
{prompt:'What happens to area when you scale all sides?',formula:'Scale by k → area × k²',why:'Both length and width get multiplied by k, so the area gets multiplied by k twice.',example:'Double sides → 4× area; triple → 9× area'},
{prompt:'How do you find surface area from a net?',formula:'Add the area of every face',why:'A net is the 3D shape unfolded flat. Find each face as a rectangle or triangle, then add them all.',example:'Cube, edge 3: 6 × 9 = 54 cm²'},
{prompt:'How do you handle fractional side lengths?',formula:'Same formula, fraction multiplication',why:'Convert mixed numbers to improper fractions, multiply numerators and denominators, then simplify.',example:'4½ × 2⅔ = 9/2 × 8/3 = 12 ft²'}]},
{id:'fractions',name:'Fractions',subtitle:'Make equal parts make sense. Multiply, divide, and reason with any fraction.',problems:[
// --- Adding and subtracting ---
{title:'Share the trail mix',text:'You mix 1/4 cup of raisins with 2/4 cup of nuts. How many cups of trail mix is that?',answer:.75,unit:'cup',shape:'text',visual:'¼ + ²⁄₄',steps:['We are combining amounts, so add.','Both amounts use fourths. Add the numerators and keep the denominator: (1 + 2)/4.','3/4 cup. You can enter 3/4 or 0.75.']},
{title:'The leftover ribbon',text:'You have 5/6 meter of ribbon and use 1/3 meter. How much remains?',answer:.5,unit:'m',shape:'text',visual:'⁵⁄₆ − ⅓',steps:['Remaining amount means subtract the part used from what you had.','Make equal-sized parts: 1/3 = 2/6. Then 5/6 − 2/6 = 3/6.','Simplify 3/6 to 1/2 meter.']},
{title:'Two hikes',text:'On Saturday you hike 2¼ miles. On Sunday you hike 1½ miles. How far did you hike in all?',answer:3.75,unit:'mi',shape:'text',visual:'2¼ + 1½',steps:['Combining distances, so add the mixed numbers.','Whole parts: 2 + 1 = 3. Fraction parts: 1/4 + 2/4 = 3/4.','3 + 3/4 = 3¾ miles, or 3.75.']},
{title:'Borrow a whole',text:'A board is 5¼ feet long. You cut off 2¾ feet. How much is left?',answer:2.5,unit:'ft',shape:'text',visual:'5¼ − 2¾',steps:['Subtract the piece cut off. But 1/4 is smaller than 3/4, so regroup.','5¼ = 4 + 5/4. Now subtract: 4 − 2 = 2 and 5/4 − 3/4 = 2/4.','2 + 2/4 = 2½ feet, or 2.5.']},
{title:'Unlike denominators',text:'A recipe calls for 2/3 cup of sugar and 1/6 cup of honey. How much sweetener is that altogether? Enter a fraction or round to 4 decimal places.',answer:5/6,decimalPlaces:4,unit:'cup',shape:'text',visual:'⅔ + ⅙',steps:['Add, but the parts are different sizes. Find a common denominator: 6.','2/3 = 4/6. Then 4/6 + 1/6 = 5/6.','5/6 cup. As a decimal that is about 0.8333.']},
// --- Multiplying ---
{title:'Half of a recipe',text:'A recipe needs 3/4 cup of milk. You make half the recipe. How much milk do you need?',answer:.375,unit:'cup',shape:'text',visual:'½ × ¾',steps:['We need half of an amount. Multiply by 1/2.','Multiply numerators and denominators: (1 × 3)/(2 × 4).','3/8 cup, or 0.375 cup.']},
{title:'Fraction of a class',text:'There are 35 students in a class. 2/5 of them ride the bus. How many students ride the bus?',answer:14,unit:'students',shape:'text',visual:'⅖ × 35',steps:['“Of” a whole number means multiply.','2/5 × 35 = (2 × 35)/5 = 70/5.','70 ÷ 5 = 14 students. Or: 35 ÷ 5 = 7 per fifth, and 2 × 7 = 14.']},
{title:'Mixed number multiply',text:'A rectangle is 1½ m by 2⅔ m. What is its area?',answer:4,unit:'m²',shape:'text',visual:'1½ × 2⅔',steps:['Area = length × width. Convert the mixed numbers first.','1½ = 3/2 and 2⅔ = 8/3. Multiply: (3 × 8)/(2 × 3) = 24/6.','24/6 = 4 m².']},
{title:'Flour left, then used',text:'You have 3/4 pound of flour. You use 2/3 of it for bread. How much flour did the bread use?',answer:.5,unit:'lb',shape:'text',visual:'⅔ × ¾',steps:['We want 2/3 of 3/4. That is multiplication.','(2 × 3)/(3 × 4) = 6/12.','Simplify: 6/12 = 1/2 pound.']},
{title:'Tiny tile',text:'A tile is 2/3 ft wide and 3/4 ft tall. What is its area?',answer:.5,unit:'ft²',shape:'text',visual:'⅔ × ¾',steps:['Area = width × height, even with fractions.','(2 × 3)/(3 × 4) = 6/12.','6/12 = 1/2 ft².']},
// --- Dividing (the 6th-grade core) ---
{title:'Little scoops',text:'You have 3/4 cup of oats. Each scoop holds 1/8 cup. How many full scoops can you fill?',answer:6,unit:'scoops',shape:'text',visual:'¾ ÷ ⅛',steps:['We want the number of equal groups. Divide total oats by the scoop size.','3/4 is 6/8. There are six eighths in that amount.','You can fill 6 scoops.']},
{title:'Flip and multiply',text:'A ribbon is 2/3 yard long. You cut it into pieces that are each 1/6 yard. How many pieces do you get?',answer:4,unit:'pieces',shape:'text',visual:'⅔ ÷ ⅙',steps:['How many 1/6-size groups fit in 2/3? Divide.','Dividing by a fraction is the same as multiplying by its reciprocal: 2/3 × 6/1 = 12/3.','12/3 = 4 pieces. Check: 2/3 = 4/6, and there are four sixths in 4/6.']},
{title:'Whole number divided by a fraction',text:'You have 5 cups of rice. One batch of the recipe uses 2/3 cup. How many batches can you make?',answer:7.5,unit:'batches',shape:'text',visual:'5 ÷ ⅔',steps:['How many 2/3-cup groups fit in 5 cups? Divide 5 by 2/3.','5 ÷ 2/3 = 5 × 3/2 = 15/2.','15/2 = 7½ batches. Seven full batches, plus half of another.']},
{title:'Fraction divided by a whole number',text:'You share 3/4 of a pizza equally among 3 friends. What fraction of the whole pizza does each friend get?',answer:.25,unit:'pizza',shape:'text',visual:'¾ ÷ 3',steps:['Splitting into equal shares: divide 3/4 by 3.','3/4 ÷ 3 = 3/4 × 1/3 = 3/12.','3/12 = 1/4 of the pizza each.']},
{title:'Dividing mixed numbers',text:'A trail is 4½ miles long. Rest stops are every 3/4 mile. How many stretches of 3/4 mile are on the trail?',answer:6,unit:'stretches',shape:'text',visual:'4½ ÷ ¾',steps:['Convert the mixed number: 4½ = 9/2.','9/2 ÷ 3/4 = 9/2 × 4/3 = 36/6.','36/6 = 6 stretches.']},
{title:'Scarves from a bolt',text:'You have 7½ yards of fabric. Each scarf needs 5/8 yard. How many scarves can you make?',answer:12,unit:'scarves',shape:'text',visual:'7½ ÷ ⅝',steps:['Equal groups of 5/8 out of 7½: divide.','7½ = 15/2. Then 15/2 × 8/5 = 120/10.','120/10 = 12 scarves.']},
{title:'Full pieces only',text:'A rope is 6 meters long. You cut pieces that are each 4/5 meter. How many full pieces can you cut?',answer:7,unit:'pieces',shape:'text',visual:'6 ÷ ⅘',steps:['Divide: 6 ÷ 4/5 = 6 × 5/4 = 30/4.','30/4 = 7½. The 1/2 means half of a piece, which is not a full piece.','7 full pieces, with 2/5 meter of rope left over.']},
{title:'Servings in a bag',text:'A bag holds 5/6 pound of almonds. One serving is 1/12 pound. How many servings are in the bag?',answer:10,unit:'servings',shape:'text',visual:'⅚ ÷ ¹⁄₁₂',steps:['Number of equal groups: divide the total by the serving size.','5/6 ÷ 1/12 = 5/6 × 12/1 = 60/6.','60/6 = 10 servings.']},
{title:'Split it in half',text:'You have 2½ liters of lemonade and pour it equally into 5 bottles. How much goes in each bottle?',answer:.5,unit:'L',shape:'text',visual:'2½ ÷ 5',steps:['Equal shares: divide the total by the number of bottles.','2½ = 5/2. Then 5/2 ÷ 5 = 5/2 × 1/5 = 5/10.','5/10 = 1/2 liter each.']},
// --- Unit rates with fractions (6.RP) ---
{title:'Speed walk',text:'You walk 1/2 mile in 1/4 hour. How many miles do you walk in 1 hour at that pace?',answer:2,unit:'mph',shape:'text',visual:'½ ÷ ¼',steps:['A rate per hour means miles ÷ hours.','1/2 ÷ 1/4 = 1/2 × 4/1 = 4/2.','4/2 = 2 miles per hour.']},
{title:'Paint per wall',text:'You use 3/4 gallon of paint to cover 2/3 of a wall. How many gallons cover one whole wall?',answer:1.125,unit:'gal',shape:'text',visual:'¾ ÷ ⅔',steps:['Gallons per wall means gallons ÷ walls.','3/4 ÷ 2/3 = 3/4 × 3/2 = 9/8.','9/8 = 1⅛ gallons, or 1.125.']},
// --- Fractions, decimals, percents ---
{title:'Fraction to decimal',text:'A race is 7/8 of a mile. Write that distance as a decimal.',answer:.875,unit:'mi',shape:'text',visual:'7 ÷ 8',steps:['A fraction is a division: 7/8 means 7 ÷ 8.','Divide: 8 goes into 7.000 → 0.875.','7/8 = 0.875 mile.']},
{title:'Out of one hundred',text:'You answered 3/20 of a quiz incorrectly. What percent is that?',answer:15,unit:'%',shape:'text',visual:'³⁄₂₀ = ?⁄₁₀₀',steps:['Percent means out of 100. Scale the fraction to a denominator of 100.','20 × 5 = 100, so multiply top and bottom by 5: 15/100.','15/100 = 15%.']},
{title:'Decimal to fraction',text:'A bolt is 0.625 inch thick. Write that as a fraction in simplest form.',answer:.625,unit:'in',shape:'text',visual:'0.625 = ⁶²⁵⁄₁₀₀₀',steps:['0.625 has three decimal places: 625/1000.','Divide top and bottom by 125.','625/1000 = 5/8 inch. Enter 5/8 or 0.625.']},
// --- Multi-step ---
{title:'Two-step lemonade',text:'You make 3¾ liters of lemonade and drink 1¼ liters. You pour the rest equally into 5 cups. How much is in each cup?',answer:.5,unit:'L',shape:'text',visual:'(3¾ − 1¼) ÷ 5',steps:['First find what is left: 3¾ − 1¼ = 2½ liters.','Then share it: 2½ ÷ 5 = 5/2 × 1/5 = 5/10.','5/10 = 1/2 liter in each cup.']},
{title:'Garden rows',text:'A garden bed is 2/3 the length of a 9-foot fence. How many 1/2-foot plants fit in a row along the bed?',answer:12,unit:'plants',shape:'text',visual:'(⅔ × 9) ÷ ½',steps:['First find the bed length: 2/3 × 9 = 6 feet.','Then count 1/2-foot groups: 6 ÷ 1/2 = 6 × 2 = 12.','12 plants fit.']}
],detectives:[
{text:'You combine 1/2 liter of juice and 1/4 liter of water. Which operation finds the total?',options:['Add','Multiply','Divide'],correct:0,why:'You are putting two amounts together. Use a common denominator, then add.'},
{text:'You need one third of a 3/4-cup serving. Which operation finds the amount?',options:['Subtract','Multiply','Divide'],correct:1,why:'You are scaling an amount to one third of its size: 1/3 × 3/4.'},
{text:'How many 1/4-meter pieces fit in 2 meters of string?',options:['Add','Subtract','Divide'],correct:2,why:'The question asks how many equal groups fit: 2 ÷ 1/4 = 8.'},
{text:'“Each bag holds 2/3 pound. How many bags for 6 pounds?” Which operation?',options:['6 × 2/3','6 ÷ 2/3','6 − 2/3'],correct:1,why:'“How many groups of a size” signals division. 6 ÷ 2/3 = 9 bags.'},
{text:'Before you divide 3½ ÷ 1¼, what should you do first?',options:['Round both to whole numbers','Convert both to improper fractions','Find a common denominator'],correct:1,why:'Rewrite as 7/2 ÷ 5/4, then multiply by the reciprocal: 7/2 × 4/5 = 28/10 = 2⅘.'},
{text:'What is the reciprocal of 2½?',options:['5/2','2/5','1/2'],correct:1,why:'2½ = 5/2. Flip it: 2/5. Do not flip the mixed number without converting first.'},
{text:'Is 8 ÷ 1/2 bigger or smaller than 8?',options:['Bigger','Smaller','The same'],correct:0,why:'Dividing by a number less than 1 asks how many small pieces fit. Sixteen halves fit in 8, so the answer grows.'},
{text:'To add 1/3 + 1/4, which common denominator is the most efficient?',options:['7','12','24'],correct:1,why:'12 is the least common multiple of 3 and 4: 4/12 + 3/12 = 7/12. Never add the denominators.'},
{text:'You ran 3/4 mile in 1/6 hour. Which finds your speed in miles per hour?',options:['3/4 × 1/6','1/6 ÷ 3/4','3/4 ÷ 1/6'],correct:2,why:'Miles per hour means miles ÷ hours: 3/4 ÷ 1/6 = 3/4 × 6 = 4½ mph.'},
{text:'Estimate 7/8 + 11/12.',options:['About 1','About 2','About 3'],correct:1,why:'Each fraction is close to 1, so the sum is close to 2. Estimating helps you catch mistakes.'},
{text:'You divide 9 ÷ 4/5 and get 11¼. You need full boxes. How many full boxes?',options:['11','12','11.25'],correct:0,why:'The ¼ means part of a box. Only 11 boxes are complete. Read what the question asks.'},
{text:'Which is larger: 5/8 or 0.6?',options:['5/8','0.6','They are equal'],correct:0,why:'5/8 = 0.625, which is greater than 0.600. Converting to decimals makes fractions easy to compare.'},
{text:'Half of a number is 3/4. Which finds the number?',options:['3/4 × 1/2','3/4 ÷ 1/2','3/4 − 1/2'],correct:1,why:'Undo “half of” with division: 3/4 ÷ 1/2 = 3/4 × 2 = 1½.'},
{text:'A recipe uses 2/3 cup of oil. You triple it. What is the best plan?',options:['3 × 2/3','2/3 ÷ 3','2/3 + 3'],correct:0,why:'Tripling means multiplying by 3: 3 × 2/3 = 6/3 = 2 cups.'}
],cards:[
{prompt:'How do you add fractions with different denominators?',formula:'Same-sized parts, then add',why:'Find a common denominator. Rewrite both fractions as equivalent fractions, then add their numerators.',example:'1/2 + 1/4 = 2/4 + 1/4 = 3/4'},
{prompt:'How do you subtract mixed numbers when the fraction is too small?',formula:'Regroup one whole into the fraction',why:'Borrow 1 from the whole number and add it to the fraction part, then subtract as usual.',example:'5¼ − 2¾ = 4⁵⁄₄ − 2¾ = 2½'},
{prompt:'How do you multiply two fractions?',formula:'a/b × c/d = ac/bd',why:'Multiply the numerators and multiply the denominators. Denominators cannot be zero. Simplify if possible.',example:'1/2 × 3/4 = 3/8'},
{prompt:'How do you find a fraction of a whole number?',formula:'a/b × n = (a × n)/b',why:'“Of” means multiply. Or divide the whole number by the denominator first, then multiply by the numerator.',example:'2/5 × 35 = 70/5 = 14'},
{prompt:'How do you divide by a nonzero fraction?',formula:'a/b ÷ c/d = a/b × d/c',why:'Multiply by the reciprocal of the divisor. Think: how many groups of that size fit? All denominators and the divisor must be nonzero.',example:'3/4 ÷ 1/8 = 3/4 × 8/1 = 6'},
{prompt:'How do you convert a mixed number to an improper fraction?',formula:'whole × denominator + numerator',why:'Each whole is one full set of parts. Count all the parts, then keep the same denominator.',example:'4½ = (4 × 2 + 1)/2 = 9/2'},
{prompt:'How do you multiply or divide mixed numbers?',formula:'Convert first, then multiply or flip',why:'Mixed numbers hide a plus sign. Turn them into improper fractions so the rules for fractions apply.',example:'1½ × 2⅔ = 3/2 × 8/3 = 4'},
{prompt:'How do you find a unit rate with fractions?',formula:'rate = amount ÷ time (or per 1 unit)',why:'“Per hour” means for 1 hour. Divide the distance by the fraction of an hour, using the reciprocal.',example:'1/2 mi ÷ 1/4 hr = 2 mph'},
{prompt:'How do you turn a fraction into a decimal?',formula:'Divide numerator by denominator',why:'A fraction bar is a division sign. Long division gives the decimal.',example:'7/8 = 7 ÷ 8 = 0.875'},
{prompt:'How do you turn a fraction into a percent?',formula:'Scale to a denominator of 100',why:'Percent means per hundred. Multiply top and bottom by the same number, or convert to a decimal and multiply by 100.',example:'3/20 = 15/100 = 15%'},
{prompt:'Why does dividing a positive number by a positive fraction less than 1 make the answer bigger?',formula:'n ÷ (small piece) = many pieces',why:'Division asks how many pieces fit. Small pieces fit many times, so the quotient can be larger than what you started with.',example:'8 ÷ 1/2 = 16'},
{prompt:'How do you check a fraction answer?',formula:'Estimate, then multiply back',why:'Round fractions to 0, ½, or 1 to estimate. For division, multiply the quotient by the divisor to get the dividend.',example:'6 × 1/8 = 6/8 = 3/4 ✓'}]},
{id:'ratios',name:'Ratios, Unit Rates & Percentages',subtitle:'Compare quantities. Find the rate for one. Think per hundred.',problems:[
// --- Ratios and equivalent ratios ---
{title:'Lemonade recipe',text:'A lemonade recipe uses 2 lemons for every 3 cups of water. You use 8 lemons. How many cups of water do you need?',answer:12,unit:'cups',shape:'text',visual:'2 : 3 = 8 : ?',steps:['The ratio lemons : water is 2 : 3. We scale both parts by the same number.','2 × 4 = 8, so multiply water by 4 too.','3 × 4 = 12 cups.']},
{title:'Class ratio',text:'The ratio of boys to girls in a class is 3 : 5. There are 24 students. How many girls are there?',answer:15,unit:'girls',shape:'text',visual:'3 + 5 = 8 parts',steps:['3 : 5 is part-to-part. Together that is 3 + 5 = 8 equal parts.','24 students ÷ 8 parts = 3 students per part.','Girls are 5 parts: 5 × 3 = 15.']},
{title:'Ratio table',text:'A bakery uses 3 cups of flour for every 2 batches of muffins. How many batches can they make with 15 cups of flour?',answer:10,unit:'batches',shape:'text',visual:'3 : 2 → 15 : ?',steps:['Build a ratio table: 3 → 2, 6 → 4, 9 → 6, 12 → 8, 15 → 10.','Or notice 15 ÷ 3 = 5, so scale by 5.','2 × 5 = 10 batches.']},
{title:'Paint mix',text:'A shade of green mixes blue and yellow in the ratio 4 : 6. You use 10 mL of blue. How much yellow?',answer:15,unit:'mL',shape:'text',visual:'4 : 6 = 2 : 3',steps:['Simplify first: 4 : 6 = 2 : 3.','10 mL blue is 2 × 5, so scale by 5.','3 × 5 = 15 mL yellow.']},
{title:'Feet to inches',text:'There are 12 inches in 1 foot. How many inches are in 7.5 feet?',answer:90,unit:'in',shape:'text',visual:'1 : 12 = 7.5 : ?',steps:['The ratio feet : inches is 1 : 12.','Scale by 7.5: 12 × 7.5.','12 × 7.5 = 90 inches.']},
{title:'Kilometers to miles',text:'8 kilometers is about 5 miles. About how many miles is a 32 km bike ride?',answer:20,unit:'mi',shape:'text',visual:'8 : 5 = 32 : ?',steps:['Use a double number line: 8 km lines up with 5 mi.','32 ÷ 8 = 4, so scale both by 4.','5 × 4 = 20 miles.']},
// --- Unit rates ---
{title:'Miles per gallon',text:'A car travels 240 miles on 8 gallons of gas. How many miles per gallon is that?',answer:30,unit:'mpg',shape:'text',visual:'240 ÷ 8',steps:['“Per gallon” means for 1 gallon. Divide miles by gallons.','240 ÷ 8 = 30.','30 miles per gallon.']},
{title:'Unit price',text:'A 5-pound bag of apples costs $6.25. What is the price per pound?',answer:1.25,unit:'$/lb',shape:'text',visual:'6.25 ÷ 5',steps:['Price per pound = total price ÷ pounds.','6.25 ÷ 5 = 1.25.','$1.25 per pound.']},
{title:'The better buy',text:'A 20-ounce box of cereal costs $4.50. What is its price per ounce, in dollars?',answer:.225,unit:'$/oz',shape:'text',visual:'4.50 ÷ 20',steps:['Unit price = cost ÷ ounces.','4.50 ÷ 20 = 0.225.','$0.225 per ounce, or 22.5 cents. Compare that to a 12 oz box at $3.00 (25 cents per ounce): the big box is the better buy.']},
{title:'Running pace',text:'You run 3 miles in 24 minutes. How many minutes per mile is that?',answer:8,unit:'min/mi',shape:'text',visual:'24 ÷ 3',steps:['Minutes per mile = minutes ÷ miles.','24 ÷ 3 = 8.','8 minutes per mile. Flipping it, 3 ÷ 24 = 0.125 miles per minute, which is 7.5 mph.']},
{title:'Words per minute',text:'You type 275 words in 5 minutes. At that rate, how many words can you type in 12 minutes?',answer:660,unit:'words',shape:'text',visual:'275 ÷ 5, then × 12',steps:['Find the unit rate first: 275 ÷ 5 = 55 words per minute.','Then scale to 12 minutes: 55 × 12.','55 × 12 = 660 words.']},
// --- Percents ---
{title:'Percent of a number',text:'A jar has 80 marbles. 30% of them are blue. How many blue marbles are there?',answer:24,unit:'marbles',shape:'text',visual:'30% × 80',steps:['30% means 30 out of 100, or 0.30, or 3/10.','0.30 × 80 = 24. Or: 10% of 80 is 8, and 3 × 8 = 24.','24 blue marbles.']},
{title:'Find the percent',text:'You got 18 questions right out of 40. What percent is that?',answer:45,unit:'%',shape:'text',visual:'18/40 = ?/100',steps:['Percent means out of 100. Scale 18/40 to hundredths.','40 × 2.5 = 100, so 18 × 2.5 = 45.','45%.']},
{title:'Find the whole',text:'25% of a class chose pizza. That was 15 students. How many students are in the class?',answer:60,unit:'students',shape:'text',visual:'25% of ? = 15',steps:['25% is 1/4. So 15 is one fourth of the whole.','If one part is 15, the whole is 4 parts: 15 × 4.','60 students.']},
{title:'Sale price',text:'A $50 hoodie is 20% off. What is the sale price?',answer:40,unit:'$',shape:'text',visual:'50 − 20% × 50',steps:['Find the discount: 20% of 50 = 0.20 × 50 = 10.','Subtract the discount from the original price.','50 − 10 = $40. Shortcut: you pay 80%, and 0.80 × 50 = 40.']},
{title:'Leave a tip',text:'Dinner costs $32. You leave a 15% tip. How much is the tip?',answer:4.8,unit:'$',shape:'text',visual:'15% × 32',steps:['10% of 32 is 3.20. 5% is half of that: 1.60.','15% = 10% + 5% = 3.20 + 1.60.','The tip is $4.80.']},
{title:'Fraction to percent',text:'7 out of 25 students walk to school. What percent walk?',answer:28,unit:'%',shape:'text',visual:'7/25 = ?/100',steps:['Scale the fraction to a denominator of 100.','25 × 4 = 100, so 7 × 4 = 28.','28%.']},
{title:'Percent bigger than 100',text:'A plant was 20 cm tall. Now it is 150% of that height. How tall is it now?',answer:30,unit:'cm',shape:'text',visual:'150% × 20',steps:['150% = 1.5. Percents over 100 mean more than the whole.','1.5 × 20 = 30.','30 cm tall.']}
],detectives:[
{text:'“3 apples for every 2 oranges” compares which kind of amounts?',options:['Part to part','Part to whole','Whole to whole'],correct:0,why:'Apples and oranges are two parts of the fruit bowl. Apples to all fruit would be 3 : 5, part to whole.'},
{text:'Which is a unit rate?',options:['$12 for 4 pounds','$3 for 1 pound','4 pounds for $12'],correct:1,why:'A unit rate compares to exactly 1 unit. $3 per pound tells you the price of one pound.'},
{text:'To find a car’s miles per gallon from 180 miles and 6 gallons, which do you compute?',options:['180 × 6','180 ÷ 6','6 ÷ 180'],correct:1,why:'Miles per gallon means miles for each 1 gallon: 180 ÷ 6 = 30. The order matters.'},
{text:'Which bag is the better buy: 8 oz for $2 or 12 oz for $2.70?',options:['8 oz for $2','12 oz for $2.70','They cost the same per ounce'],correct:1,why:'Compare unit prices: $2 ÷ 8 = 25¢ per oz, and $2.70 ÷ 12 = 22.5¢ per oz. Lower cost per ounce wins.'},
{text:'What does 35% mean?',options:['35 out of 10','35 out of 100','35 out of 1000'],correct:1,why:'Percent means per hundred. 35% = 35/100 = 0.35.'},
{text:'To find 40% of 90, which is correct?',options:['90 ÷ 40','0.40 × 90','90 − 40'],correct:1,why:'“Of” means multiply. 40% = 0.40, and 0.40 × 90 = 36.'},
{text:'12 is 50% of a number. How do you find the number?',options:['12 × 0.5','12 ÷ 0.5','12 − 0.5'],correct:1,why:'Undo “50% of” with division: 12 ÷ 0.5 = 24. Or think: if half is 12, the whole is 24.'},
{text:'A ratio table shows 4 : 10 and 6 : 15. Which pair also belongs?',options:['8 : 12','10 : 25','5 : 11'],correct:1,why:'Both rows equal 2 : 5. Multiply 2 : 5 by 5 to get 10 : 25. Adding the same number to both sides breaks the ratio.'},
{text:'A store marks a $60 jacket 25% off. What do you pay?',options:['$25','$45','$35'],correct:1,why:'25% of 60 = 15. Then 60 − 15 = 45. Or pay 75%: 0.75 × 60 = 45.'}
],cards:[
{prompt:'What is a ratio?',formula:'a : b, or a to b, or a/b',why:'A ratio compares two quantities by multiplication. It can compare part to part or part to whole.',example:'2 lemons : 3 cups water'},
{prompt:'How do you find equivalent ratios?',formula:'Multiply or divide both parts by the same number',why:'Scaling both quantities keeps the relationship the same. Adding the same number does not.',example:'2 : 3 = 8 : 12 = 10 : 15'},
{prompt:'How do you use a ratio with a total?',formula:'Total ÷ (sum of parts) = size of one part',why:'A tape diagram shows the parts. Find the value of one part, then multiply.',example:'3 : 5 with 24 total → 3 per part → 15 girls'},
{prompt:'What is a unit rate?',formula:'amount ÷ units = amount per 1 unit',why:'A unit rate compares to exactly one: per mile, per hour, per pound. It makes comparing easy.',example:'240 mi ÷ 8 gal = 30 mpg'},
{prompt:'How do you find the better buy?',formula:'Compare unit prices',why:'Divide price by quantity to get cost per one unit. The lower unit price is the better deal.',example:'$4.50 ÷ 20 oz = 22.5¢ per oz'},
{prompt:'What does percent mean?',formula:'% = per 100',why:'A percent is a ratio out of 100. Convert with fractions or decimals: 45% = 45/100 = 0.45.',example:'7/25 = 28/100 = 28%'},
{prompt:'How do you find a percent of a number?',formula:'percent as decimal × number',why:'“Of” means multiply. Use 10% as a benchmark: 10% is one tenth, and other percents build from it.',example:'30% of 80 = 0.3 × 80 = 24'},
{prompt:'How do you find the whole from a percent?',formula:'part ÷ percent = whole',why:'If you know the part and what percent it is, divide to undo the multiplication.',example:'15 ÷ 0.25 = 60'},
{prompt:'How do you find a sale price?',formula:'price × (100% − discount%)',why:'Either subtract the discount or multiply by the percent you still pay.',example:'$50 × 0.80 = $40'}]},
{id:'baseten',name:'Arithmetic in Base Ten',subtitle:'Decimals, long division, and the factors that hold numbers together.',problems:[
// --- Long division ---
{title:'Team buses',text:'1,344 students are going on a field trip. Each bus holds 32 students. How many buses are needed?',answer:42,unit:'buses',shape:'text',visual:'1,344 ÷ 32',steps:['Equal groups of 32, so divide.','32 × 40 = 1,280. That leaves 64. 32 × 2 = 64.','40 + 2 = 42 buses, with no students left over.']},
{title:'Decimal quotient',text:'A ribbon 315 cm long is cut into 12 equal pieces. How long is each piece?',answer:26.25,unit:'cm',shape:'text',visual:'315 ÷ 12',steps:['Divide 315 by 12. 12 × 26 = 312, remainder 3.','Keep dividing: 3.00 ÷ 12 = 0.25.','Each piece is 26.25 cm.']},
{title:'Big division',text:'A factory packs 2,652 pencils into boxes of 17. How many boxes?',answer:156,unit:'boxes',shape:'text',visual:'2,652 ÷ 17',steps:['Estimate: 17 × 150 = 2,550. Close.','2,652 − 2,550 = 102, and 17 × 6 = 102.','150 + 6 = 156 boxes.']},
// --- Adding and subtracting decimals ---
{title:'Two receipts',text:'You spend $4.75 at lunch and $12.60 at the store. How much did you spend?',answer:17.35,unit:'$',shape:'text',visual:'4.75 + 12.60',steps:['Line up the decimal points so tenths add to tenths.','4.75 + 12.60: 0.75 + 0.60 = 1.35, and 4 + 12 = 16.','16 + 1.35 = $17.35.']},
{title:'Change back',text:'You pay with a $20 bill for a $7.85 item. How much change do you get?',answer:12.15,unit:'$',shape:'text',visual:'20.00 − 7.85',steps:['Write 20 as 20.00 so the places line up.','Count up: 7.85 + 0.15 = 8, then 8 + 12 = 20.','0.15 + 12 = $12.15.']},
{title:'Track times',text:'One runner finishes in 58.4 seconds and another in 56.75 seconds. How much faster is the second runner?',answer:1.65,unit:'s',shape:'text',visual:'58.40 − 56.75',steps:['Difference means subtract. Pad 58.4 to 58.40.','58.40 − 56.75: borrow, then subtract.','1.65 seconds.']},
// --- Multiplying decimals ---
{title:'Fabric cost',text:'Fabric costs $2.50 per meter. You buy 3.4 meters. How much do you pay?',answer:8.5,unit:'$',shape:'text',visual:'3.4 × 2.5',steps:['Multiply as whole numbers: 34 × 25 = 850.','Count decimal places: 3.4 has one, 2.5 has one. Two total.','850 → 8.50. You pay $8.50.']},
{title:'Tiny product',text:'Compute 0.06 × 1.5.',answer:.09,unit:'',shape:'text',visual:'0.06 × 1.5',steps:['Whole numbers first: 6 × 15 = 90.','Decimal places: 0.06 has two, 1.5 has one. Three total.','90 → 0.090 = 0.09. Multiplying by a number less than 1 makes the answer smaller.']},
{title:'Four of them',text:'Four notebooks cost $2.35 each. What is the total?',answer:9.4,unit:'$',shape:'text',visual:'4 × 2.35',steps:['4 × 2.35: 4 × 2 = 8 and 4 × 0.35 = 1.40.','8 + 1.40 = 9.40.','$9.40.']},
{title:'Tenths times tenths',text:'A square sticker has sides of 0.4 cm. What is its area?',answer:.16,unit:'cm²',shape:'text',visual:'0.4 × 0.4',steps:['4 × 4 = 16.','Two decimal places in all: 0.16.','0.16 cm². A tenth of a tenth is a hundredth.']},
// --- Dividing decimals ---
{title:'Decimal divisor',text:'How many 0.8-liter bottles can you fill from 7.2 liters of juice?',answer:9,unit:'bottles',shape:'text',visual:'7.2 ÷ 0.8',steps:['Dividing by a decimal: shift both numbers one place so the divisor is whole: 72 ÷ 8.','72 ÷ 8 = 9.','9 bottles. Shifting both by ×10 does not change the quotient.']},
{title:'Price per pound',text:'3.5 pounds of grapes cost $15.75. What is the price per pound?',answer:4.5,unit:'$/lb',shape:'text',visual:'15.75 ÷ 3.5',steps:['Shift one place: 157.5 ÷ 35.','35 × 4 = 140, remainder 17.5. 35 × 0.5 = 17.5.','4 + 0.5 = $4.50 per pound.']},
{title:'Splitting the bill',text:'Six friends split a $52.50 bill equally. How much does each pay?',answer:8.75,unit:'$',shape:'text',visual:'52.50 ÷ 6',steps:['Divide: 6 × 8 = 48, remainder 4.50.','4.50 ÷ 6 = 0.75.','$8.75 each.']},
// --- Estimation ---
{title:'Estimate, then compute',text:'A school orders 21 boxes of 498 pencils. How many pencils in total?',answer:10458,unit:'pencils',shape:'text',visual:'498 × 21',steps:['Estimate first: 500 × 20 = 10,000.','498 × 21 = 498 × 20 + 498 = 9,960 + 498.','10,458 pencils. Close to the estimate, so it checks out.']},
// --- GCF and LCM ---
{title:'Greatest common factor',text:'You have 24 pencils and 36 erasers. You want identical gift bags with nothing left over. What is the greatest number of bags?',answer:12,unit:'bags',shape:'text',visual:'GCF(24, 36)',steps:['Each bag gets the same number of pencils and erasers, so the bag count divides both 24 and 36.','Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24. Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36.','The greatest shared factor is 12 bags (2 pencils and 3 erasers each).']},
{title:'Least common multiple',text:'Hot dogs come in packs of 6 and buns in packs of 8. What is the smallest number of hot dogs you can buy with no extra buns or hot dogs?',answer:24,unit:'hot dogs',shape:'text',visual:'LCM(6, 8)',steps:['You need a number that is a multiple of both 6 and 8.','Multiples of 6: 6, 12, 18, 24. Multiples of 8: 8, 16, 24.','24 is the least common multiple: 4 packs of hot dogs and 3 packs of buns.']},
{title:'Factor it out',text:'Rewrite 36 + 48 as a multiple of a sum with no common factor: ? × (3 + 4). What is the missing number?',answer:12,unit:'',shape:'text',visual:'36 + 48 = ? × (3 + 4)',steps:['Find the GCF of 36 and 48. Factors of 36: …12, 18, 36. Factors of 48: …12, 16, 24, 48.','The GCF is 12. 36 = 12 × 3 and 48 = 12 × 4.','36 + 48 = 12 × (3 + 4) = 12 × 7 = 84.']},
{title:'Blinking lights',text:'One light blinks every 9 seconds and another every 12 seconds. They blink together now. In how many seconds will they blink together again?',answer:36,unit:'s',shape:'text',visual:'LCM(9, 12)',steps:['They meet at a common multiple of 9 and 12.','Multiples of 9: 9, 18, 27, 36. Multiples of 12: 12, 24, 36.','36 seconds.']}
],detectives:[
{text:'When you add 3.7 + 12.45, what do you line up?',options:['The last digits','The decimal points','The first digits'],correct:1,why:'Lining up decimal points matches tenths with tenths and hundredths with hundredths. 3.70 + 12.45 = 16.15.'},
{text:'2.5 × 1.2: the whole-number product is 300. Where does the decimal point go?',options:['3.00','30.0','0.300'],correct:0,why:'Count the decimal places in the factors: one plus one is two. 300 becomes 3.00.'},
{text:'Which is true about 40 × 0.5?',options:['Bigger than 40','Smaller than 40','Equal to 40'],correct:1,why:'Multiplying by a number less than 1 shrinks the result. 40 × 0.5 = 20.'},
{text:'To divide 9.6 ÷ 0.4, what is a good first move?',options:['Move both decimals one place: 96 ÷ 4','Divide 96 by 0.4','Round 0.4 to 1'],correct:0,why:'Multiplying both numbers by 10 keeps the quotient the same and makes the divisor whole: 96 ÷ 4 = 24.'},
{text:'You want the largest number of identical goody bags from 18 candies and 30 stickers. Which do you need?',options:['GCF','LCM','The product'],correct:0,why:'The bag count must divide both amounts. The greatest common factor is 6 bags.'},
{text:'Two buses leave the station every 10 and 15 minutes. When do they leave together again? Which do you need?',options:['GCF','LCM','The sum'],correct:1,why:'You need a shared multiple of both times. The least common multiple is 30 minutes.'},
{text:'A recipe calls for 2.3 cups per batch and you make 4 batches. Which estimate is best?',options:['About 6 cups','About 9 cups','About 12 cups'],correct:1,why:'2.3 is a little more than 2, so 4 × 2.3 is a little more than 8. The exact answer is 9.2.'},
{text:'147 ÷ 6 = 24 remainder 3. As a decimal, the answer is:',options:['24.3','24.5','24.6'],correct:1,why:'The remainder 3 out of 6 is half. 3 ÷ 6 = 0.5, so 24.5.'},
{text:'Which shows the distributive property with the GCF?',options:['20 + 30 = 5(4 + 6)','20 + 30 = 10(2 + 3)','20 + 30 = 2(10 + 15)'],correct:1,why:'All three are true, but only 10 is the greatest common factor of 20 and 30, leaving 2 + 3 with no common factor.'}
],cards:[
{prompt:'How do you add or subtract decimals?',formula:'Line up the decimal points',why:'Same place values must combine: tenths with tenths, hundredths with hundredths. Add zeros to fill empty places.',example:'20.00 − 7.85 = 12.15'},
{prompt:'How do you multiply decimals?',formula:'Multiply, then count decimal places',why:'Multiply as whole numbers. The product has as many decimal places as both factors combined.',example:'3.4 × 2.5 → 34 × 25 = 850 → 8.50'},
{prompt:'How do you divide by a decimal?',formula:'Shift both numbers until the divisor is whole',why:'Multiplying dividend and divisor by the same power of 10 does not change the quotient.',example:'7.2 ÷ 0.8 = 72 ÷ 8 = 9'},
{prompt:'How do you do long division?',formula:'Divide, multiply, subtract, bring down',why:'Work one place at a time. Estimate with multiples of the divisor, then check by multiplying back.',example:'1,344 ÷ 32 = 42'},
{prompt:'What is the greatest common factor (GCF)?',formula:'Largest number that divides both',why:'List the factors of each number and pick the biggest shared one. Use it for splitting into equal groups.',example:'GCF(24, 36) = 12'},
{prompt:'What is the least common multiple (LCM)?',formula:'Smallest number both divide into',why:'List multiples of each number until one matches. Use it for events that repeat and line up.',example:'LCM(6, 8) = 24'},
{prompt:'How does the distributive property use the GCF?',formula:'a + b = GCF × (a÷GCF + b÷GCF)',why:'Factor the shared piece out of a sum. The numbers left inside share no common factor.',example:'36 + 48 = 12(3 + 4)'},
{prompt:'Why estimate first?',formula:'Round, compute, compare',why:'An estimate catches decimal-point mistakes. If the exact answer is far from the estimate, recheck.',example:'498 × 21 ≈ 500 × 20 = 10,000'}]},
{id:'expressions',name:'Expressions & Equations',subtitle:'Let a letter stand for a number. Then find it.',problems:[
// --- Exponents and order of operations ---
{title:'Power up',text:'Compute 2⁵.',answer:32,unit:'',shape:'text',visual:'2 × 2 × 2 × 2 × 2',steps:['An exponent tells how many times to use the base as a factor.','2 × 2 × 2 × 2 × 2 = 32.','2⁵ = 32, not 2 × 5 = 10.']},
{title:'Order matters',text:'Evaluate 4 + 6 × 2².',answer:28,unit:'',shape:'text',visual:'4 + 6 × 2²',steps:['Exponents first: 2² = 4.','Then multiply: 6 × 4 = 24.','Then add: 4 + 24 = 28.']},
{title:'Cube volume',text:'The volume of a cube is V = s³. What is the volume when s = 4 cm?',answer:64,unit:'cm³',shape:'text',visual:'4³',steps:['Substitute s = 4 into s³.','4 × 4 × 4 = 64.','64 cm³.']},
{title:'Parentheses first',text:'Evaluate (3 + 5)² − 10 ÷ 2.',answer:59,unit:'',shape:'text',visual:'(3 + 5)² − 10 ÷ 2',steps:['Parentheses: 3 + 5 = 8. Exponent: 8² = 64.','Division: 10 ÷ 2 = 5.','64 − 5 = 59.']},
// --- Evaluating expressions ---
{title:'Plug it in',text:'Evaluate 3x + 5 when x = 4.',answer:17,unit:'',shape:'text',visual:'3(4) + 5',steps:['Replace x with 4. 3x means 3 × x.','3 × 4 = 12.','12 + 5 = 17.']},
{title:'Words to symbols',text:'“7 less than twice a number n.” Evaluate it when n = 9.',answer:11,unit:'',shape:'text',visual:'2n − 7',steps:['Twice a number: 2n. Seven less than that: 2n − 7.','Substitute n = 9: 2 × 9 − 7.','18 − 7 = 11.']},
{title:'Two variables',text:'Evaluate 2a + 3b when a = 5 and b = 2.',answer:16,unit:'',shape:'text',visual:'2(5) + 3(2)',steps:['Substitute each variable: 2 × 5 + 3 × 2.','10 + 6.','16.']},
{title:'Fraction coefficient',text:'Evaluate ½ y + 4 when y = 10.',answer:9,unit:'',shape:'text',visual:'½(10) + 4',steps:['½ y means half of y.','Half of 10 is 5.','5 + 4 = 9.']},
// --- Equivalent expressions ---
{title:'Combine like terms',text:'Simplify 4x + 3x + 2, then evaluate when x = 5.',answer:37,unit:'',shape:'text',visual:'7x + 2',steps:['4x and 3x are like terms: 4x + 3x = 7x.','The expression is 7x + 2.','7 × 5 + 2 = 37.']},
{title:'Distribute',text:'Rewrite 3(x + 4) without parentheses, then evaluate when x = 2.',answer:18,unit:'',shape:'text',visual:'3x + 12',steps:['Multiply 3 by each term inside: 3 × x + 3 × 4 = 3x + 12.','Substitute x = 2: 3 × 2 + 12.','6 + 12 = 18. Check: 3(2 + 4) = 3 × 6 = 18. Same.']},
{title:'Factor it',text:'Write 6x + 9 as a product: 3(2x + ?). What is the missing number?',answer:3,unit:'',shape:'text',visual:'6x + 9 = 3(2x + ?)',steps:['The GCF of 6 and 9 is 3.','6x ÷ 3 = 2x and 9 ÷ 3 = 3.','6x + 9 = 3(2x + 3). The missing number is 3.']},
// --- Solving one-step equations ---
{title:'Undo addition',text:'Solve x + 7 = 15.',answer:8,unit:'',shape:'text',visual:'x + 7 = 15',steps:['x has 7 added to it. Undo with subtraction on both sides.','x + 7 − 7 = 15 − 7.','x = 8. Check: 8 + 7 = 15.']},
{title:'Undo multiplication',text:'Solve 5y = 45.',answer:9,unit:'',shape:'text',visual:'5y = 45',steps:['5y means 5 × y. Undo with division on both sides.','45 ÷ 5 = 9.','y = 9. Check: 5 × 9 = 45.']},
{title:'Undo division',text:'Solve m ÷ 4 = 6.',answer:24,unit:'',shape:'text',visual:'m/4 = 6',steps:['m is divided by 4. Undo with multiplication on both sides.','6 × 4 = 24.','m = 24. Check: 24 ÷ 4 = 6.']},
{title:'Decimal equation',text:'Solve x − 3.5 = 10.',answer:13.5,unit:'',shape:'text',visual:'x − 3.5 = 10',steps:['Undo subtraction with addition.','10 + 3.5 = 13.5.','x = 13.5.']},
{title:'Fraction equation',text:'Solve ⅔ x = 8.',answer:12,unit:'',shape:'text',visual:'⅔ x = 8',steps:['x is multiplied by 2/3. Undo by multiplying both sides by the reciprocal, 3/2.','8 × 3/2 = 24/2.','x = 12. Check: 2/3 × 12 = 8.']},
{title:'Pencils for six dollars',text:'Pencils cost $0.75 each. You spend $6.00. Write and solve an equation for the number of pencils p.',answer:8,unit:'pencils',shape:'text',visual:'0.75p = 6',steps:['Cost per pencil × number of pencils = total: 0.75p = 6.','Divide both sides by 0.75: 6 ÷ 0.75.','p = 8 pencils.']},
// --- Inequalities and dependent variables ---
{title:'Largest whole number',text:'What is the largest whole number that makes x + 3 < 10 true?',answer:6,unit:'',shape:'text',visual:'x + 3 < 10',steps:['Undo the 3: x < 7.','x must be less than 7, not equal to 7.','The largest whole number is 6. On a number line, an open circle at 7 with an arrow to the left.']},
{title:'Age limit',text:'A ride requires a height h of at least 42 inches: h ≥ 42. Is 42 allowed? Enter the smallest allowed height.',answer:42,unit:'in',shape:'text',visual:'h ≥ 42',steps:['“At least” means greater than or equal to.','42 itself satisfies h ≥ 42.','The smallest allowed height is 42. Closed circle on the number line.']},
{title:'Dependent variable',text:'A car goes 4 miles per minute on a race track: d = 4t. How far does it go in 7 minutes?',answer:28,unit:'mi',shape:'text',visual:'d = 4t',steps:['t is the independent variable (you choose the time). d depends on t.','Substitute t = 7: d = 4 × 7.','d = 28 miles.']},
{title:'Read the table',text:'A table shows y = 3x + 1: when x = 1, y = 4; x = 2, y = 7; x = 3, y = 10. What is y when x = 10?',answer:31,unit:'',shape:'text',visual:'y = 3x + 1',steps:['The rule is y = 3x + 1. Each step in x adds 3 to y.','Substitute x = 10: 3 × 10 + 1.','y = 31.']}
],detectives:[
{text:'What does 5³ mean?',options:['5 × 3','5 × 5 × 5','5 + 5 + 5'],correct:1,why:'The exponent counts how many times the base is a factor: 5 × 5 × 5 = 125.'},
{text:'In 8 − 2 × 3, what do you do first?',options:['8 − 2','2 × 3','Either'],correct:1,why:'Multiplication comes before subtraction: 8 − 6 = 2. Doing 8 − 2 first gives 18, which is wrong.'},
{text:'Which equation matches: “A number divided by 4 is 12”?',options:['4n = 12','n ÷ 4 = 12','n − 4 = 12'],correct:1,why:'“Divided by 4” is n ÷ 4. The word “is” means equals.'},
{text:'To solve n − 9 = 20, what do you do to both sides?',options:['Subtract 9','Add 9','Divide by 9'],correct:1,why:'Undo subtraction with addition. n = 29.'},
{text:'Which expression is equivalent to 2(x + 5)?',options:['2x + 5','2x + 10','x + 10'],correct:1,why:'Distribute the 2 to both terms: 2 × x + 2 × 5 = 2x + 10. Try x = 1: both give 12.'},
{text:'Which are like terms?',options:['3x and 3y','3x and 5x','3x and 3'],correct:1,why:'Like terms have the same variable. 3x + 5x = 8x. You cannot combine 3x and 3.'},
{text:'In the equation 6x = 42, what is x?',options:['A number you add','The unknown value that makes it true','The answer 6'],correct:1,why:'A variable stands for an unknown. Only x = 7 makes 6x = 42 true.'},
{text:'How do you graph x > 3 on a number line?',options:['Closed circle at 3, arrow right','Open circle at 3, arrow right','Open circle at 3, arrow left'],correct:1,why:'“Greater than” does not include 3, so use an open circle. Values to the right are bigger.'},
{text:'“y is the cost, x is the number of tickets.” Which is the independent variable?',options:['y','x','Neither'],correct:1,why:'You choose the number of tickets; the cost depends on it. Independent = the one you control.'},
{text:'Does x = 5 make 3x + 1 = 16 true?',options:['Yes','No','Cannot tell'],correct:0,why:'Substitute: 3 × 5 + 1 = 16. Checking a solution means substituting and seeing if both sides match.'}
],cards:[
{prompt:'What does an exponent mean?',formula:'bⁿ = b × b × … (n times)',why:'The base is the repeated factor. The exponent counts how many. b² is squared, b³ is cubed.',example:'2⁵ = 32'},
{prompt:'What is the order of operations?',formula:'Parentheses, Exponents, × ÷ (left to right), + − (left to right)',why:'Everyone agrees on this order so an expression has one value. Multiplication and division are equal partners.',example:'4 + 6 × 2² = 4 + 24 = 28'},
{prompt:'How do you evaluate an expression?',formula:'Substitute, then follow the order of operations',why:'Replace each variable with its value. Remember 3x means 3 × x.',example:'3x + 5 at x = 4 → 17'},
{prompt:'What is the distributive property?',formula:'a(b + c) = ab + ac',why:'Multiply the outside number by every term inside. It works backward too, to factor.',example:'3(x + 4) = 3x + 12'},
{prompt:'How do you combine like terms?',formula:'Add the coefficients, keep the variable',why:'Like terms have exactly the same variable part. 4 x-things plus 3 x-things is 7 x-things.',example:'4x + 3x + 2 = 7x + 2'},
{prompt:'How do you solve a one-step equation?',formula:'Do the inverse operation to both sides',why:'Addition undoes subtraction; division undoes multiplication. Keep the equation balanced.',example:'5y = 45 → y = 9'},
{prompt:'How do you check a solution?',formula:'Substitute it back in',why:'A solution makes the equation true. If both sides are equal, you are right.',example:'x = 8: 8 + 7 = 15 ✓'},
{prompt:'How do you graph an inequality?',formula:'Open circle for < or >, closed for ≤ or ≥',why:'Inequalities have infinitely many solutions. The arrow shows all of them.',example:'x < 7: open circle at 7, arrow left'},
{prompt:'What are independent and dependent variables?',formula:'dependent = rule(independent)',why:'The independent variable is the input you pick. The dependent variable changes because of it.',example:'d = 4t: t is independent, d depends on t'}]},
{id:'rationals',name:'Rational Numbers',subtitle:'Below zero. Left of zero. Every point on the line has a name.',problems:[
// --- Negatives in context ---
{title:'Cold morning',text:'At 6 a.m. it is −8°C. By noon the temperature rises 15 degrees. What is the noon temperature?',answer:7,unit:'°C',shape:'text',visual:'−8 → +15',steps:['Start at −8 on a number line. Rising means moving right.','From −8, moving 8 to the right reaches 0. That leaves 7 more.','0 + 7 = 7°C.']},
{title:'Bank balance',text:'Your account balance is −$25. You deposit $40. What is the new balance?',answer:15,unit:'$',shape:'text',visual:'−25 → +40',steps:['A negative balance means you owe money. A deposit moves right.','25 of the 40 brings you to 0.','40 − 25 = 15. The balance is $15.']},
{title:'Below and above',text:'A diver is at −30 feet. A bird is at 45 feet. How far apart are they vertically?',answer:75,unit:'ft',shape:'text',visual:'|−30| + |45|',steps:['They are on opposite sides of sea level (zero).','Distance from −30 up to 0 is 30. From 0 up to 45 is 45.','30 + 45 = 75 feet apart.']},
{title:'Freezer to kitchen',text:'A freezer is −18°C and the kitchen is 22°C. What is the temperature difference?',answer:40,unit:'°C',shape:'text',visual:'|−18| + |22|',steps:['Find the distance between the two numbers on a number line.','−18 is 18 below zero; 22 is 22 above.','18 + 22 = 40 degrees.']},
// --- Opposites and absolute value ---
{title:'Absolute value',text:'What is |−12|?',answer:12,unit:'',shape:'text',visual:'|−12|',steps:['Absolute value is the distance from zero.','−12 is 12 units from 0.','|−12| = 12. Distance is never negative.']},
{title:'The opposite',text:'What is the opposite of −7?',answer:7,unit:'',shape:'text',visual:'−(−7)',steps:['Opposites are the same distance from zero on opposite sides.','−7 is 7 to the left of 0. Its opposite is 7 to the right.','The opposite of −7 is 7.']},
{title:'How much is owed?',text:'A balance of −$45 means money is owed. How many dollars are owed?',answer:45,unit:'$',shape:'text',visual:'|−45|',steps:['The sign tells direction (owed). The absolute value tells the size.','|−45| = 45.','$45 is owed.']},
{title:'Steps left',text:'Start at 1 on a number line and move 3.5 units to the left. Where do you land?',answer:-2.5,unit:'',shape:'text',visual:'1 → −3.5',steps:['Moving left means subtracting. 1 unit gets you to 0.','You still need to move 2.5 more to the left.','You land at −2.5.']},
{title:'Fraction on the line',text:'Write −3/4 as a decimal.',answer:-.75,unit:'',shape:'text',visual:'−¾',steps:['3/4 = 0.75.','The negative sign keeps it on the left side of zero.','−3/4 = −0.75.']},
// --- Ordering ---
{title:'Count the colder days',text:'Daily lows this week: −5, −1, −3, 0, 2, −7, 4. How many days were colder than −2°C?',answer:3,unit:'days',shape:'text',visual:'< −2',steps:['Colder than −2 means less than −2, which is further left on the number line.','−5, −3, and −7 are all left of −2. −1 is warmer (to the right).','3 days.']},
{title:'Deepest dive',text:'Three divers are at −12 m, −20 m, and −15 m. How many meters deep is the deepest diver?',answer:20,unit:'m',shape:'text',visual:'−20 < −15 < −12',steps:['The smallest number is the deepest: −20 < −15 < −12.','Depth is the absolute value: |−20| = 20.','20 meters deep.']},
// --- Coordinate plane ---
{title:'Same row',text:'How far is it from (−3, 4) to (5, 4)?',answer:8,unit:'units',shape:'text',visual:'|−3| + |5|',steps:['Both points have y = 4, so they are on the same horizontal line.','−3 is 3 units left of the y-axis; 5 is 5 units right.','3 + 5 = 8 units.']},
{title:'Same column',text:'How far is it from (2, −6) to (2, 3)?',answer:9,unit:'units',shape:'text',visual:'|−6| + |3|',steps:['Both points have x = 2: same vertical line.','−6 is 6 below the x-axis; 3 is 3 above.','6 + 3 = 9 units.']},
{title:'Which quadrant?',answerLabel:'Quadrant number (1–4)',text:'The point (−3, −8) is in which quadrant? Enter 1, 2, 3, or 4.',answer:3,unit:'',shape:'text',visual:'(−, −)',steps:['Quadrants are numbered counterclockwise starting from the upper right.','Negative x means left; negative y means down. That is the lower left.','Quadrant 3.']},
{title:'Mirror image',text:'The point (−4, 7) is reflected across the x-axis. What is the y-coordinate of the new point?',answer:-7,unit:'',shape:'text',visual:'(−4, 7) → (−4, ?)',steps:['Reflecting across the x-axis flips up and down. The x-coordinate stays the same.','The y-coordinate becomes its opposite.','New point: (−4, −7). The y-coordinate is −7.']},
{title:'Fence the rectangle',text:'A rectangle has vertices (−2, 1), (4, 1), (4, −3), and (−2, −3). What is its perimeter?',answer:20,unit:'units',shape:'text',visual:'2 × (6 + 4)',steps:['Horizontal side: from −2 to 4 is 2 + 4 = 6 units.','Vertical side: from 1 to −3 is 1 + 3 = 4 units.','Perimeter = 2 × (6 + 4) = 20 units.']},
{title:'Area with negatives',text:'Using the same rectangle with vertices (−2, 1), (4, 1), (4, −3), (−2, −3), what is its area?',answer:24,unit:'units²',shape:'text',visual:'6 × 4',steps:['Side lengths are distances, so they are positive: 6 and 4.','Area = length × width.','6 × 4 = 24 square units.']}
],detectives:[
{text:'Which is colder: −4°C or −9°C?',options:['−4°C','−9°C','Same'],correct:1,why:'−9 is further left on the number line, so it is smaller and colder. With negatives, a bigger digit means a smaller number.'},
{text:'Which statement is true?',options:['−3 > 2','−3 < −1','−3 > 0'],correct:1,why:'−3 is to the left of −1 on the number line, so −3 < −1. All negatives are less than 0 and less than every positive.'},
{text:'What is |−6|?',options:['−6','6','0'],correct:1,why:'Absolute value is distance from zero, always positive or zero.'},
{text:'Which is greater: −8 or |−8|?',options:['−8','|−8|','Equal'],correct:1,why:'|−8| = 8. Absolute value can be larger than the number itself when the number is negative.'},
{text:'What is the opposite of the opposite of 5?',options:['−5','5','0'],correct:1,why:'−(−5) = 5. Taking the opposite twice brings you back.'},
{text:'A point has a positive x and a negative y. Which quadrant?',options:['Quadrant 1','Quadrant 2','Quadrant 4'],correct:2,why:'Positive x is right; negative y is down. Lower right is Quadrant 4.'},
{text:'Which point is a reflection of (3, 5) across the y-axis?',options:['(3, −5)','(−3, 5)','(−3, −5)'],correct:1,why:'Reflecting across the y-axis flips left and right, so only the x-coordinate changes sign.'},
{text:'“A debt of $20” is written as:',options:['20','−20','|20|'],correct:1,why:'Debts, losses, and amounts below zero use negative numbers. The sign shows direction.'},
{text:'How far apart are −4 and 6 on a number line?',options:['2','10','−10'],correct:1,why:'From −4 to 0 is 4; from 0 to 6 is 6. Total 10. Distance is always positive.'},
{text:'Which list is in order from least to greatest?',options:['−1, −5, 0, 3','−5, −1, 0, 3','0, −1, −5, 3'],correct:1,why:'Reading left to right on the number line: −5, −1, 0, 3.'}
],cards:[
{prompt:'What are negative numbers?',formula:'Numbers less than 0',why:'They show amounts below zero or in the opposite direction: temperatures, debts, depths, losses.',example:'−8°C, −$25, −30 ft'},
{prompt:'What are opposites?',formula:'a and −a',why:'Opposites are the same distance from 0 on opposite sides. The opposite of the opposite is the original.',example:'−(−7) = 7'},
{prompt:'What is absolute value?',formula:'|a| = distance from 0',why:'It measures size without direction, so it is never negative.',example:'|−12| = 12, |12| = 12'},
{prompt:'How do you compare negative numbers?',formula:'Further left = smaller',why:'On a number line, values increase to the right. −9 is left of −4, so −9 < −4.',example:'−9 < −4 < 0 < 3'},
{prompt:'How do you find the distance between two numbers?',formula:'Count the gap on the number line',why:'If they are on opposite sides of 0, add their absolute values. If on the same side, subtract them.',example:'−30 to 45: 30 + 45 = 75'},
{prompt:'What are the four quadrants?',formula:'I (+,+), II (−,+), III (−,−), IV (+,−)',why:'Numbered counterclockwise from the upper right. Signs of x and y tell you which one.',example:'(−3, −8) is in Quadrant III'},
{prompt:'How do reflections change coordinates?',formula:'Across x-axis: (x, −y). Across y-axis: (−x, y)',why:'Reflecting flips one direction. The coordinate that changes is the one perpendicular to the axis.',example:'(−4, 7) → (−4, −7) across the x-axis'},
{prompt:'How do you find a side length on the coordinate plane?',formula:'Distance between coordinates that differ',why:'Points on the same horizontal or vertical line share one coordinate. The other coordinates give the distance.',example:'(−3, 4) to (5, 4): 3 + 5 = 8'}]},
{id:'data',name:'Data Sets & Distributions',subtitle:'Ask a question. Collect answers. See the shape of the data.',problems:[
// --- Measures of center ---
{title:'Mean score',text:'Quiz scores: 7, 9, 12, 8, 14. What is the mean?',answer:10,unit:'',shape:'text',visual:'50 ÷ 5',steps:['Mean = total ÷ number of values.','7 + 9 + 12 + 8 + 14 = 50.','50 ÷ 5 = 10.']},
{title:'Median, odd count',text:'Data: 3, 8, 5, 12, 7. What is the median?',answer:7,unit:'',shape:'text',visual:'3, 5, [7], 8, 12',steps:['Order the data first: 3, 5, 7, 8, 12.','The median is the middle value. With 5 values, it is the 3rd.','The median is 7.']},
{title:'Median, even count',text:'Data: 4, 9, 6, 11. What is the median?',answer:7.5,unit:'',shape:'text',visual:'4, [6, 9], 11',steps:['Order: 4, 6, 9, 11. With 4 values there are two middle numbers.','Average the middle two: (6 + 9) ÷ 2.','15 ÷ 2 = 7.5.']},
{title:'Mode',text:'Shoe sizes in a group: 2, 5, 5, 7, 9, 5, 2. What is the mode?',answer:5,unit:'',shape:'text',visual:'5 appears 3 times',steps:['The mode is the value that appears most often.','5 appears three times; 2 appears twice.','The mode is 5.']},
{title:'Balance point',text:'Data: 10, 10, 10, 20. What is the mean?',answer:12.5,unit:'',shape:'text',visual:'50 ÷ 4',steps:['Total: 10 + 10 + 10 + 20 = 50.','50 ÷ 4 = 12.5.','The mean is the balance point of the dot plot. One high value pulls it above the median of 10.']},
{title:'Missing test score',text:'Your first three test scores are 80, 90, and 78. What score on the fourth test gives you a mean of 85?',answer:92,unit:'',shape:'text',visual:'85 × 4 − (80 + 90 + 78)',steps:['A mean of 85 over 4 tests means a total of 85 × 4 = 340.','So far: 80 + 90 + 78 = 248.','340 − 248 = 92.']},
{title:'Total from the mean',text:'Six players score a mean of 12 points each. How many points did the team score in total?',answer:72,unit:'points',shape:'text',visual:'12 × 6',steps:['Mean = total ÷ count, so total = mean × count.','12 × 6.','72 points.']},
{title:'Dot plot mean',text:'A dot plot shows 2 dots at 1, 5 dots at 2, and 3 dots at 3. What is the mean?',answer:2.1,unit:'',shape:'text',visual:'(2·1 + 5·2 + 3·3) ÷ 10',steps:['Count the dots: 2 + 5 + 3 = 10 values.','Total: 2 × 1 + 5 × 2 + 3 × 3 = 2 + 10 + 9 = 21.','21 ÷ 10 = 2.1.']},
{title:'The outlier',text:'Data: 5, 6, 7, 8 has a mean of 6.5. Add a fifth value, 24. What is the new mean?',answer:10,unit:'',shape:'text',visual:'50 ÷ 5',steps:['New total: 5 + 6 + 7 + 8 + 24 = 50.','50 ÷ 5 = 10.','The mean jumped from 6.5 to 10. The median only moved from 6.5 to 7. Outliers pull the mean.']},
// --- Measures of spread ---
{title:'Range',text:'Temperatures this week: 15, 22, 9, 30, 18. What is the range?',answer:21,unit:'',shape:'text',visual:'30 − 9',steps:['Range = maximum − minimum.','Max is 30, min is 9.','30 − 9 = 21.']},
{title:'Mean absolute deviation',text:'Data: 2, 4, 6, 8. Find the mean absolute deviation (MAD).',answer:2,unit:'',shape:'text',visual:'(3 + 1 + 1 + 3) ÷ 4',steps:['Mean: (2 + 4 + 6 + 8) ÷ 4 = 5.','Distance of each value from the mean: 3, 1, 1, 3.','Mean of those distances: 8 ÷ 4 = 2. On average, values are 2 away from the mean.']},
{title:'Quartiles',text:'Data: 3, 5, 7, 8, 10, 12, 15, 20. What is the interquartile range (IQR)?',answer:7.5,unit:'',shape:'text',visual:'Q3 − Q1',steps:['Median: (8 + 10) ÷ 2 = 9. Lower half: 3, 5, 7, 8 → Q1 = (5 + 7) ÷ 2 = 6.','Upper half: 10, 12, 15, 20 → Q3 = (12 + 15) ÷ 2 = 13.5.','IQR = 13.5 − 6 = 7.5. The middle half of the data spans 7.5.']},
{title:'Box plot',text:'A box plot has minimum 10, Q1 14, median 18, Q3 25, and maximum 30. What is the IQR?',answer:11,unit:'',shape:'text',visual:'25 − 14',steps:['The box runs from Q1 to Q3.','IQR = Q3 − Q1 = 25 − 14.','11. The whiskers show the range: 30 − 10 = 20.']},
{title:'MAD with decimals',text:'Data: 10, 12, 14, 20. Find the MAD.',answer:3,unit:'',shape:'text',visual:'(4 + 2 + 0 + 6) ÷ 4',steps:['Mean: 56 ÷ 4 = 14.','Distances from 14: 4, 2, 0, 6.','(4 + 2 + 0 + 6) ÷ 4 = 12 ÷ 4 = 3.']},
// --- Displays ---
{title:'Histogram gap',text:'A histogram of 40 test scores shows 8 students in 0–59 and 22 students in 80–100. How many scored 60–79?',answer:10,unit:'students',shape:'text',visual:'40 − 8 − 22',steps:['The bars account for all 40 students.','8 + 22 = 30 are in the other two bins.','40 − 30 = 10 students.']},
{title:'Reading a dot plot',text:'A dot plot of siblings: 4 dots at 0, 7 at 1, 5 at 2, 2 at 3, 1 at 5. How many students have more than 1 sibling?',answer:8,unit:'students',shape:'text',visual:'5 + 2 + 1',steps:['More than 1 means 2, 3, or 5 siblings.','5 + 2 + 1.','8 students. The lone dot at 5 is an outlier.']},
{title:'Frequency table',answerLabel:'Number of people',text:'Ages at a party: 11, 12, 11, 13, 12, 11, 14, 12, 11. How many people are the modal age?',answer:4,unit:'people',shape:'text',visual:'11: ||||',steps:['Tally each age: 11 → 4, 12 → 3, 13 → 1, 14 → 1.','The mode is 11.','4 people are age 11.']}
],detectives:[
{text:'Which is a statistical question?',options:['How tall am I?','How tall are the students in my class?','How tall is the door?'],correct:1,why:'A statistical question expects variability in the answers. Heights in a class vary; one person’s height is a single value.'},
{text:'Data: 12, 13, 14, 15, 90. Which measure of center describes a typical value better?',options:['Mean','Median','Range'],correct:1,why:'The outlier 90 drags the mean up to 28.8. The median, 14, is not affected. Range is a measure of spread, not center.'},
{text:'Which measures spread?',options:['Mean','Median','Interquartile range'],correct:2,why:'Range, IQR, and MAD describe how spread out data is. Mean and median describe center.'},
{text:'A MAD of 2 means:',options:['The mean is 2','Values are typically 2 away from the mean','The range is 2'],correct:1,why:'MAD averages each value’s distance from the mean. It tells how tightly the data clusters.'},
{text:'You want to show individual values for 15 data points. Which display?',options:['Dot plot','Histogram','Box plot'],correct:0,why:'Dot plots show each value. Histograms group into bins and box plots show five summary numbers.'},
{text:'You have 500 data points and want to see their shape. Which display?',options:['Dot plot','Histogram','List them'],correct:1,why:'Histograms group large data sets into intervals so the shape is visible without 500 dots.'},
{text:'A box plot’s box stretches from 14 to 25. What percent of the data is inside the box?',options:['About 25%','About 50%','About 100%'],correct:1,why:'The box spans Q1 to Q3, the middle half of the data.'},
{text:'A dot plot has a long tail to the right. Where is the mean compared to the median?',options:['Left of the median','Right of the median','Same place'],correct:1,why:'A long tail pulls the mean toward it. The median stays in the middle of the counts.'},
{text:'Which pair goes together?',options:['Mean and IQR','Median and MAD','Median and IQR'],correct:2,why:'Median and IQR both come from ordering the data and resist outliers. Mean and MAD both use every value.'},
{text:'The median of 6 values is the:',options:['3rd value','4th value','Average of the 3rd and 4th'],correct:2,why:'With an even count there is no single middle value, so average the two middle ones (after ordering).'}
],cards:[
{prompt:'What is a statistical question?',formula:'A question with varying answers',why:'It asks about a group, and the answers differ from person to person. That variability is what statistics studies.',example:'“How many pets do students in our grade have?”'},
{prompt:'How do you find the mean?',formula:'sum ÷ count',why:'The mean is the fair share if everything were evened out, and the balance point of a dot plot.',example:'(7 + 9 + 12 + 8 + 14) ÷ 5 = 10'},
{prompt:'How do you find the median?',formula:'Order, then take the middle',why:'Half the values are below and half above. With an even count, average the two middle values.',example:'3, 5, 7, 8, 12 → 7'},
{prompt:'What is the mode?',formula:'Most frequent value',why:'There can be one mode, several, or none. It is the only center that works for non-number data.',example:'2, 5, 5, 7, 5 → mode 5'},
{prompt:'What is the range?',formula:'max − min',why:'The simplest measure of spread. One outlier can make it very large.',example:'30 − 9 = 21'},
{prompt:'What is the mean absolute deviation (MAD)?',formula:'mean of |value − mean|',why:'Find each value’s distance from the mean, then average those distances. Smaller MAD means tighter data.',example:'2, 4, 6, 8 → MAD 2'},
{prompt:'What is the interquartile range (IQR)?',formula:'Q3 − Q1',why:'Q1 is the median of the lower half; Q3 is the median of the upper half. IQR measures the middle 50%.',example:'Q3 13.5 − Q1 6 = 7.5'},
{prompt:'What does a box plot show?',formula:'min, Q1, median, Q3, max',why:'The five-number summary. The box is the middle half; whiskers reach the extremes.',example:'10 | 14 [18] 25 | 30'},
{prompt:'When do you use mean vs. median?',formula:'Symmetric → mean. Skewed or outliers → median',why:'Outliers pull the mean toward them. The median only cares about position, so it stays put.',example:'12, 13, 14, 15, 90 → median 14'},
{prompt:'Dot plot, histogram, or box plot?',formula:'Dot: every value. Histogram: bins. Box: summary',why:'Choose by data size and what you want to see: individual values, overall shape, or center and spread.',example:'500 scores → histogram'}]}
];
