import type { Topic } from './types';
export const LEGACY_CURRICULUM: Topic[] = [
{id:'area',name:'Area',subtitle:'Explore area. See the space. Solve the mystery.',problems:[
{title:'A space for your ideas',text:'Your rectangular art board is 8 cm long and 5 cm wide. How much space is there for your artwork?',answer:40,unit:'cm²',shape:'rectangle',a:8,b:5,steps:['Find the space inside the board. That means area, measured in square units.','A rectangle has rows of equal squares. Use area = length × width.','Substitute: 8 × 5 = 40. The area is 40 cm².']},
{title:'Build a reading nook',text:'A square rug has sides of 6 feet. What area of the floor will it cover?',answer:36,unit:'ft²',shape:'square',a:6,b:6,steps:['We want the floor covered, so find area.','A square is a rectangle with equal sides: area = side × side.','6 × 6 = 36 square feet.']},
{title:'Design a pennant',text:'A triangular pennant has a base of 10 cm and a perpendicular height of 6 cm. What is its area?',answer:30,unit:'cm²',shape:'triangle',a:10,b:6,steps:['Find the space inside the triangle. The height is perpendicular to the base.','A triangle takes up half of a matching parallelogram: area = base × height ÷ 2.','10 × 6 ÷ 2 = 30 cm².']},
{title:'A slanted splash of color',text:'A parallelogram sticker has a base of 9 cm and a perpendicular height of 4 cm. Find its area.',answer:36,unit:'cm²',shape:'parallelogram',a:9,b:4,steps:['Use the perpendicular height, not the slanted side.','Sliding a triangular piece from one side to the other makes a rectangle. Area = base × height.','9 × 4 = 36 cm².']},
{title:'The garden mystery',text:'A rectangular garden has an area of 48 m² and a length of 8 m. How wide is it?',answer:6,unit:'m',shape:'rectangle',a:8,b:'?',steps:['We already know the area. The missing measurement is width, in meters.','Area = length × width, so 48 = 8 × width. Undo multiplication with division.','48 ÷ 8 = 6. The width is 6 m.']},
{title:'A tiny studio',text:'A rectangular tabletop is 2.5 m long and 1.2 m wide. How much surface area does it have?',answer:3,unit:'m²',shape:'rectangle',a:2.5,b:1.2,steps:['Surface area here means the flat top, a rectangle.','Use length × width: 2.5 × 1.2.','25 × 12 = 300. Put back two decimal places: 3.00 m².']},
{title:'Room for two',text:'A craft mat is made from two non-overlapping rectangles. One is 6 cm by 4 cm; the other is 3 cm by 2 cm. What is their total area?',answer:30,unit:'cm²',shape:'text',visual:'24 + 6',steps:['The two pieces do not overlap, so we can add their areas.','First rectangle: 6 × 4 = 24 cm². Second rectangle: 3 × 2 = 6 cm².','24 + 6 = 30 cm² in all.']},
{title:'One last triangle',text:'A triangular sail has a base of 7 m and a perpendicular height of 5 m. Find its area.',answer:17.5,unit:'m²',shape:'triangle',a:7,b:5,steps:['Find area using the base and perpendicular height.','Area = base × height ÷ 2.','7 × 5 = 35. Half of 35 is 17.5 m².']}
],detectives:[
{text:'You want enough tiles to cover a rectangular floor. What should you find?',options:['Area','Perimeter','Volume'],correct:0,why:'Tiles cover the inside surface. Area measures that coverage in square units.'},
{text:'Ribbon goes once around the edge of a picture frame. What should you find?',options:['Area','Perimeter','Volume'],correct:1,why:'The ribbon follows the boundary. Perimeter measures distance around, in length units.'},
{text:'How much water can a fish tank hold?',options:['Area','Perimeter','Volume'],correct:2,why:'Water fills three-dimensional space. Volume measures capacity, rather than a flat surface.'},
{text:'A garden has area 35 m² and length 7 m. You need its width. Which plan works?',options:['Multiply 35 by 7','Divide 35 by 7','Add 35 and 7'],correct:1,why:'The relationship is 35 = 7 × width. Divide to find the missing factor. “Area” in the story does not always mean multiply the given numbers.'},
{text:'A triangular sign has base 12 cm, perpendicular height 5 cm, and a slanted side 8 cm. Which measurements find its area?',options:['12 and 8','5 and 8','12 and 5'],correct:2,why:'Use the base and perpendicular height: 12 × 5 ÷ 2. The slanted side is extra information.'}
],cards:[
{prompt:'How do you find the area of a rectangle?',formula:'A = length × width',why:'Think of rows of unit squares. The number in each row × the number of rows gives the total.',example:'8 cm × 5 cm = 40 cm²'},
{prompt:'How do you find the area of a triangle?',formula:'A = base × height ÷ 2',why:'Two matching triangles make a parallelogram. Use a height that meets the base at a right angle.',example:'10 cm × 6 cm ÷ 2 = 30 cm²'},
{prompt:'How do you find the area of a parallelogram?',formula:'A = base × height',why:'Move a triangular end to the other side to form a rectangle. Height is the perpendicular distance between the bases.',example:'9 cm × 4 cm = 36 cm²'},
{prompt:'How do you find the area of a square?',formula:'A = side × side = s²',why:'A square has equal length and width. Squared means multiply the side by itself, not by two.',example:'6 ft × 6 ft = 36 ft²'}]},
{id:'fractions',name:'Fractions',subtitle:'Make equal parts make sense. A starter exploration.',problems:[
{title:'Share the trail mix',text:'You mix 1/4 cup of raisins with 2/4 cup of nuts. How many cups of trail mix is that?',answer:.75,unit:'cup',shape:'text',visual:'¼ + ²⁄₄',steps:['We are combining amounts, so add.','Both amounts use fourths. Add the numerators and keep the denominator: (1 + 2)/4.','3/4 cup. You can enter 3/4 or 0.75.']},
{title:'The leftover ribbon',text:'You have 5/6 meter of ribbon and use 1/3 meter. How much remains?',answer:.5,unit:'m',shape:'text',visual:'⁵⁄₆ − ⅓',steps:['Remaining amount means subtract the part used from what you had.','Make equal-sized parts: 1/3 = 2/6. Then 5/6 − 2/6 = 3/6.','Simplify 3/6 to 1/2 meter.']},
{title:'Half of a recipe',text:'A recipe needs 3/4 cup of milk. You make half the recipe. How much milk do you need?',answer:.375,unit:'cup',shape:'text',visual:'½ × ¾',steps:['We need half of an amount. Multiply by 1/2.','Multiply numerators and denominators: (1 × 3)/(2 × 4).','3/8 cup, or 0.375 cup.']},
{title:'Little scoops',text:'You have 3/4 cup of oats. Each scoop holds 1/8 cup. How many full scoops can you fill?',answer:6,unit:'scoops',shape:'text',visual:'¾ ÷ ⅛',steps:['We want the number of equal groups. Divide total oats by the scoop size.','3/4 is 6/8. There are six eighths in that amount.','You can fill 6 scoops.']}
],detectives:[
{text:'You combine 1/2 liter of juice and 1/4 liter of water. Which operation finds the total?',options:['Add','Multiply','Divide'],correct:0,why:'You are putting two amounts together. Use a common denominator, then add.'},
{text:'You need one third of a 3/4-cup serving. Which operation finds the amount?',options:['Subtract','Multiply','Divide'],correct:1,why:'You are scaling an amount to one third of its size: 1/3 × 3/4.'},
{text:'How many 1/4-meter pieces fit in 2 meters of string?',options:['Add','Subtract','Divide'],correct:2,why:'The question asks how many equal groups fit: 2 ÷ 1/4 = 8.'}
],cards:[
{prompt:'How do you add fractions with different denominators?',formula:'Same-sized parts, then add',why:'Find a common denominator. Rewrite both fractions as equivalent fractions, then add their numerators.',example:'1/2 + 1/4 = 2/4 + 1/4 = 3/4'},
{prompt:'How do you multiply two fractions?',formula:'a/b × c/d = ac/bd',why:'Multiply the numerators and multiply the denominators. Denominators cannot be zero. Simplify if possible.',example:'1/2 × 3/4 = 3/8'},
{prompt:'How do you divide by a nonzero fraction?',formula:'a/b ÷ c/d = a/b × d/c',why:'Multiply by the reciprocal of the divisor. Think: how many groups of that size fit? All denominators and the divisor must be nonzero.',example:'3/4 ÷ 1/8 = 3/4 × 8/1 = 6'}]}
];
